-- APPROVED: owner (Maxboy) 2026-06-05 — Leverage #5 HITL director-approval gate.
-- hitl_approvals.id was NOT NULL with NO sequence/default (drift from drift-fix-03b-missing-tables.sql)
-- so every INSERT failed the NOT NULL constraint. Add an identity so PoRequiresDirectorApprovalListener
-- can persist HITL approval requests (the Director dashboard reads hitl_approvals). Table was empty (0 rows).
ALTER TABLE hitl_approvals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
