-- APPROVED: owner schema-approval 2026-07-11 (Muslimbek, chat) — Q-35
-- §2 Taksonomiya SEED — egasi 2026-07-11 tasdiqlagan ro'yxatlar (CRUD orqali o'zgartiriladi).
INSERT INTO taxonomy_entries (category, code, name_uz, sort_order)
SELECT * FROM (VALUES
  ('product_type', 'gofrakarton_list', 'Gofrakarton list', 1),
  ('product_type', 'gofrokorob', 'Gofrokorob', 2),
  ('product_type', 'mikrogofrokorob', 'Mikrogofrokorob', 3),
  ('product_type', 'latok', 'Latok', 4),
  ('product_type', 'tray_podnos', 'Tray/podnos', 5),
  ('product_type', 'fleksopechat_qadoq', 'Fleksopechat qadoq', 6),
  ('product_type', 'ofset_qadoq', 'Ofset qadoq', 7),
  ('product_type', 'kashirovka_mahsuloti', 'Kashirovka mahsuloti', 8),
  ('product_type', 'tigel_mahsuloti', 'Tigel mahsuloti', 9),
  ('product_type', 'palletli_qadoq', 'Palletli qadoq', 10),
  ('product_type', 'displey_qadoq', 'Displey qadoq', 11),
  ('product_type', 'rulon_gofra', 'Rulon (gofra)', 12),
  ('product_type', 'list_yassi_karton', 'List (yassi karton)', 13),
  ('product_type', 'boyalgan_laminatsiyali_qadoq', 'Bo''yalgan/laminatsiyali qadoq', 14),
  ('product_type', 'maxsus_buyurtma', 'Maxsus buyurtma', 15),
  ('discount_type', 'mavsumiy', 'Mavsumiy', 1),
  ('discount_type', 'ulgurji_hajm', 'Ulgurji (hajm)', 2),
  ('discount_type', 'sodiq_mijoz', 'Sodiq mijoz', 3),
  ('discount_type', 'oldindan_tolov', 'Oldindan to''lov', 4),
  ('discount_type', 'aksiya_promo', 'Aksiya/promo', 5),
  ('decoration_type', 'laminatsiya_yaltiroq_mat', 'Laminatsiya (yaltiroq/mat)', 1),
  ('decoration_type', 'uv_lak_toliq_spot', 'UV-lak (to''liq/spot)', 2),
  ('decoration_type', 'oddiy_lak', 'Oddiy lak', 3),
  ('document_type', 'tex_karta', 'Tex karta', 1),
  ('document_type', 'ish_rejasi', 'Ish rejasi', 2),
  ('document_type', 'sifat_hisoboti', 'Sifat hisoboti', 3),
  ('document_type', 'smena_topshirigi', 'Smena topshirig''i', 4),
  ('document_type', 'xavfsizlik_brifingi', 'Xavfsizlik brifingi', 5),
  ('document_type', 'nazorat_varaqasi', 'Nazorat varaqasi', 6),
  ('kanban_stage', 'navbatda', 'Navbatda', 1),
  ('kanban_stage', 'flekso', 'Flekso', 2),
  ('kanban_stage', 'yuqori_bosma', 'Yuqori bosma', 3),
  ('kanban_stage', 'kesish_vysechka', 'Kesish/Vysechka', 4),
  ('kanban_stage', 'kashirovka', 'Kashirovka', 5),
  ('kanban_stage', 'qadoqlash', 'Qadoqlash', 6),
  ('kanban_stage', 'tayyor', 'Tayyor', 7),
  ('supplier_type', 'xom_ashyo', 'Xom-ashyo', 1),
  ('supplier_type', 'uskuna_ehtiyot_qism', 'Uskuna/ehtiyot qism', 2),
  ('supplier_type', 'kimyoviy_moddalar', 'Kimyoviy moddalar', 3),
  ('supplier_type', 'xizmat_transport', 'Xizmat (transport)', 4),
  ('supplier_type', 'tamirlash', 'Ta''mirlash', 5),
  ('supplier_type', 'boshqa', 'Boshqa', 6),
  ('rejection_reason', 'sifat_nomos', 'Sifat nomos', 1),
  ('rejection_reason', 'miqdor_xato', 'Miqdor xato', 2),
  ('rejection_reason', 'kechikish', 'Kechikish', 3),
  ('rejection_reason', 'narx_nomos', 'Narx nomos', 4),
  ('rejection_reason', 'hujjat_nomukammal', 'Hujjat nomukammal', 5),
  ('rejection_reason', 'boshqa', 'Boshqa', 6),
  ('paper_class', 'topliner', 'Topliner', 1),
  ('paper_class', 'mahalliy_mestny', 'Mahalliy (mestny)', 2),
  ('paper_class', 'testliner', 'Testliner', 3),
  ('paper_class', 'flyuting', 'Flyuting', 4),
  ('expense_category', 'xom_ashyo', 'Xom-ashyo', 1),
  ('expense_category', 'ish_haqi', 'Ish haqi', 2),
  ('expense_category', 'kommunal', 'Kommunal', 3),
  ('expense_category', 'transport', 'Transport', 4),
  ('expense_category', 'tamirlash', 'Ta''mirlash', 5),
  ('expense_category', 'marketing', 'Marketing', 6),
  ('expense_category', 'ijara', 'Ijara', 7),
  ('expense_category', 'soliq', 'Soliq', 8),
  ('expense_category', 'boshqa', 'Boshqa', 9),
  ('notification_category', 'buyruq', 'Buyruq', 1),
  ('notification_category', 'ogohlantirish', 'Ogohlantirish', 2),
  ('notification_category', 'talab', 'Talab', 3),
  ('notification_category', 'tasdiqlash_sorovi', 'Tasdiqlash so''rovi', 4),
  ('notification_category', 'hisobot', 'Hisobot', 5),
  ('notification_category', 'elon', 'E''lon', 6),
  ('org_policy_series', 'xavfsizlik', 'Xavfsizlik', 1),
  ('org_policy_series', 'sifat', 'Sifat', 2),
  ('org_policy_series', 'mehnat_intizomi', 'Mehnat intizomi', 3),
  ('org_policy_series', 'moliyaviy', 'Moliyaviy', 4),
  ('org_policy_series', 'boshqa', 'Boshqa', 5),
  ('manager_note_category', 'mijoz_istagi', 'Mijoz istagi', 1),
  ('manager_note_category', 'shikoyat', 'Shikoyat', 2),
  ('manager_note_category', 'takliflar', 'Takliflar', 3),
  ('manager_note_category', 'muammo', 'Muammo', 4),
  ('manager_note_category', 'ijobiy_fikr', 'Ijobiy fikr', 5),
  ('code_prefix', 'kt', 'KT — Korobka tartibi', 1),
  ('code_prefix', 'pt', 'PT — Paddon tartibi', 2),
  ('code_prefix', 'e', 'E — Etiketka', 3),
  ('code_prefix', 'gl', 'GL — Gofra list', 4)
) AS v(category, code, name_uz, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM taxonomy_entries t WHERE t.category = v.category AND t.code = v.code);
