/**
 * @module pos.module
 * @description NestJS @Module() definition. Providers, controllers, and imports for this feature slice.
 */

import { Module } from '@nestjs/common';
import { CqrsModule } from '@nestjs/cqrs';
import {
  PosGateway,
  // Controllers
  PosStubController, CashRegisterController, PosPrinterConfigV2Controller,
  MovementsController, BarcodeController, RequestsController, InventoryCountController,
  EmployeeController, ReportsController, MiniAppController, MiniAppHistoryController,
  PrinterConfigController, StockController, GlController, SyncController,
  PosNotificationsController, PosAuthController, InventoryPassportController,
  PosWmsController, WarehouseFeaturesController,
  // Repos & services
  PosInventoryPassportRepository, PosInventoryPassportService, PosFifoService,
  PosLowStockJob, PosQuarantineCheckJob, PosFifoRecalculateJob, PosInactiveMaterialsJob,
  CashRegisterService, CashRegisterRepository, PosAuthService, PosAuthRepository,
  PosMovementService, PosMovementRepository, PosMovementStatusService, PosMovementStatusRepository,
  PosMovementQueryService, PosBarcodeService, PosBarcodeRepository, PosBarcodeExtService, PosBarcodeExtRepository,
  PosInventoryCountQueryService, PosInventoryCountQueryRepository,
  PosRequestService, PosRequestRepository, PosRequestExtService, PosRequestExtRepository,
  PosInventoryCountService, PosInventoryCountRepository,
  PosAuditService, PosAuditRepository, PosMovementQueryRepository,
  LabelRepository, PosPrinterConfigRepository,
  PosTelegramService, PosTelegramRepository, PosTelegramExtService, PosTelegramExtRepository,
  PosPdfService, PosPdfRepository, PosPdfInventoryService, PosPdfInventoryRepository,
  LabelService, LabelExtService, PosMiniAppService, PosMiniAppRepository,
  PosPrinterConfigService, PosReportsService, PosReportsRepository,
  StockLedgerService, GlPostingLogService, PosGlAutoService, PosBalanceGuardService,
  PosSyncService, PosNotificationsService,
  StockLedgerRepository, GlPostingLogRepository, PosSyncRepository, PosNotificationsRepository,
  LifecycleBlockService, PosLifecycleBlockRepository,
  StockReservationService, PosStockReservationRepository,
  EmployeeLedgerService, EmployeeLedgerRepository,
  EmployeeWriteOffService, EmployeeWriteOffRepository,
  PosInventoryService, PosInventoryRepository,
  PosService, DrizzlePosSvcRepository, POS_SVC_REPO,
  PosEventHandler, PosSecondaryEventsHandler, PosEventRepository, PosDepartmentGuard,
  PosRequisitionWorkflowService, PosEmployeeBalanceService,
  PosWmsSyncService, PosWmsQueryService,
  WarehouseEmployeesService, AutoBarcodeService, Material360Service, AutoGlPostingService,
  WarehouseKpiService, GoodsReceiptService, QuarantineWorkflowService, ThreeWayMatchService,
  SmsService, EmailService, TelegramBotService, QueueService,
  WarehouseEmployeesRepository, GoodsReceiptRepository, AutoBarcodeRepository, WarehouseKpiRepository,
  QuarantineWorkflowRepository, ThreeWayMatchRepository, AutoGlPostingRepository, PosEmployeeBalanceRepository,
} from './pos.module-imports';

@Module({
  imports: [CqrsModule],
  controllers: [
    PosStubController,
    CashRegisterController,
    PosPrinterConfigV2Controller,
    MovementsController,
    BarcodeController,
    RequestsController,
    InventoryCountController,
    EmployeeController,
    ReportsController,
    MiniAppController,
    MiniAppHistoryController,
    PrinterConfigController,
    StockController,
    GlController,
    SyncController,
    PosNotificationsController,
    PosAuthController,
    InventoryPassportController,
    PosWmsController,
    WarehouseFeaturesController,
  ],
  providers: [
    { provide: POS_SVC_REPO, useClass: DrizzlePosSvcRepository },
    CashRegisterRepository,
    CashRegisterService,
    PosService,
    PosMovementRepository,
    PosMovementService,
    PosMovementStatusRepository,
    PosMovementStatusService,
    PosMovementQueryService,
    PosBarcodeRepository,
    PosBarcodeService,
    PosBarcodeExtRepository,
    PosBarcodeExtService,
    PosRequestRepository,
    PosRequestService,
    PosRequestExtRepository,
    PosRequestExtService,
    PosInventoryCountRepository,
    PosInventoryCountService,
    PosInventoryCountQueryRepository,
    PosInventoryCountQueryService,
    PosAuditRepository,
    PosAuditService,
    PosAuthRepository,
    PosAuthService,
    PosMovementQueryRepository,
    PosTelegramRepository,
    PosTelegramService,
    PosTelegramExtRepository,
    PosTelegramExtService,
    PosPdfRepository,
    PosPdfService,
    PosPdfInventoryRepository,
    PosPdfInventoryService,
    LabelRepository,
    LabelService,
    LabelExtService,
    PosLifecycleBlockRepository,
    LifecycleBlockService,
    PosStockReservationRepository,
    StockReservationService,
    EmployeeLedgerRepository,
    EmployeeLedgerService,
    EmployeeWriteOffRepository,
    EmployeeWriteOffService,
    PosEventHandler,
    PosSecondaryEventsHandler,
    PosEventRepository,
    PosDepartmentGuard,
    PosMiniAppRepository,
    PosMiniAppService,
    PosPrinterConfigRepository,
    PosPrinterConfigService,
    PosReportsRepository,
    PosReportsService,
    PosInventoryService,
    PosInventoryRepository,
    StockLedgerRepository,
    StockLedgerService,
    GlPostingLogRepository,
    GlPostingLogService,
    PosGlAutoService,
    PosBalanceGuardService,
    PosSyncRepository,
    PosSyncService,
    PosNotificationsRepository,
    PosNotificationsService,
    PosGateway,
    PosInventoryPassportRepository,
    PosInventoryPassportService,
    PosFifoService,
    PosLowStockJob,
    PosQuarantineCheckJob,
    PosFifoRecalculateJob,
    PosRequisitionWorkflowService,
    PosEmployeeBalanceService,
    PosWmsSyncService,
    PosWmsQueryService,
    PosInactiveMaterialsJob,
    // Warehouse features — repositories (Sprint B)
    WarehouseEmployeesRepository,
    GoodsReceiptRepository,
    AutoBarcodeRepository,
    WarehouseKpiRepository,
    QuarantineWorkflowRepository,
    ThreeWayMatchRepository,
    AutoGlPostingRepository,
    PosEmployeeBalanceRepository,
    // Warehouse features — services
    WarehouseEmployeesService,
    AutoBarcodeService,
    Material360Service,
    AutoGlPostingService,
    WarehouseKpiService,
    GoodsReceiptService,
    QuarantineWorkflowService,
    ThreeWayMatchService,
    SmsService,
    EmailService,
    TelegramBotService,
    QueueService,
  ],
  exports: [
    POS_SVC_REPO,
    PosService,
    PosMovementService,
    PosMovementStatusService,
    PosMovementQueryService,
    PosBarcodeService,
    PosBarcodeExtService,
    PosRequestService,
    PosRequestExtService,
    PosInventoryCountService,
    PosInventoryCountQueryService,
    EmployeeLedgerService,
    StockReservationService,
    PosAuditService,
    PosPdfService,
    PosPdfInventoryService,
    LabelService,
    LabelExtService,
    StockLedgerService,
    GlPostingLogService,
    PosNotificationsService,
    PosInventoryPassportService,
    PosFifoService,
    PosRequisitionWorkflowService,
    PosEmployeeBalanceService,
  ],
})
export class PosModule {}
