/**
 * @module pos.module
 * @description NestJS @Module() definition. Providers, controllers, and imports for this feature slice.
 */

import { Module } from '@nestjs/common';
import { CqrsModule } from '@nestjs/cqrs';
import { ProcurementApprovalChainService } from './application/services/procurement-approval-chain.service';
import { ProcurementController } from './presentation/procurement.controller';
import { WarehouseConfigController } from './presentation/warehouse-config.controller';
import { ProcurementRequestService } from './application/services/procurement-request.service';
import { WarehouseConfigService } from './application/services/warehouse-config.service';
import {
  PosGateway,
  // Controllers
  PosStubController, CashRegisterController, PosPrinterConfigV2Controller,
  MovementsController, ShiftHandoverController, BarcodeController, RequestsController, InventoryCountController,
  PosShiftHandoverService, PosShiftHandoverRepository,
  EmployeeController, ReportsController, MiniAppController, MiniAppHistoryController,
  PrinterConfigController, StockController, GlController, SyncController,
  PosNotificationsController, PosAnomaliesController, PosAuthController, InventoryPassportController,
  PosWmsController, WarehouseFeaturesController, PosOperationsController,
  WarehouseOpenController, WarehouseOpenService, WarehouseOpenRepository,
  // BE-T2-BARCODE-RESERV — KIRIM barkod-gen + CHIQIM bron-blok
  StockIssuableController, PosStockIssuableService, PosStockIssuableRepository,
  // Repos & services
  PosInventoryPassportRepository, PosInventoryPassportService, PosFifoService,
  PosLowStockJob, PosQuarantineCheckJob, PosFifoRecalculateJob, PosInactiveMaterialsJob,
  CashRegisterService, CashRegisterRepository, PosAuthService, PosAuthRepository,
  PosMovementService, PosMovementRepository, PosMovementStatusService, PosMovementStatusRepository,
  PosMovementQueryService, PosBarcodeService, PosBarcodeRepository, PosBarcodeExtService, PosBarcodeExtRepository,
  PosInventoryCountQueryService, PosInventoryCountQueryRepository,
  PosRequestService, PosRequestRepository, PosRequestExtService, PosRequestExtRepository,
  PosInventoryCountService, PosInventoryCountRepository,
  PosAuditService, PosAuditRepository, PosMovementQueryRepository,
  LabelRepository, PosPrinterConfigRepository,
  PosTelegramService, PosTelegramRepository, PosTelegramExtService, PosTelegramExtRepository,
  PosPdfService, PosPdfRepository, PosPdfInventoryService, PosPdfInventoryRepository,
  LabelService, LabelExtService, PosMiniAppService, PosMiniAppRepository,
  PosPrinterConfigService, PosReportsService, PosReportsRepository,
  StockLedgerService, GlPostingLogService, PosGlAutoService, PosBalanceGuardService,
  PosSyncService, PosNotificationsService,
  StockLedgerRepository, GlPostingLogRepository, PosSyncRepository, PosNotificationsRepository,
  LifecycleBlockService, PosLifecycleBlockRepository,
  StockReservationService, PosStockReservationRepository,
  EmployeeLedgerService, EmployeeLedgerRepository,
  EmployeeWriteOffService, EmployeeWriteOffRepository,
  PosInventoryService, PosInventoryRepository,
  PosService, DrizzlePosSvcRepository, POS_SVC_REPO,
  PosEventHandler, PosSecondaryEventsHandler, PosEventRepository, PosDepartmentGuard,
  PosWmsSyncCreatedListener,
  PosAnomalyService, PosAnomalyRepository, PosAnomalyListener,
  PosRequisitionWorkflowService, PosEmployeeBalanceService,
  PosWmsSyncService, PosWmsQueryService,
  WarehouseEmployeesService, AutoBarcodeService, Material360Service, AutoGlPostingService,
  WarehouseKpiService, GoodsReceiptService, QuarantineWorkflowService, ThreeWayMatchService,
  SmsService, EmailService, TelegramBotService, QueueService,
  WarehouseEmployeesRepository, GoodsReceiptRepository, AutoBarcodeRepository, WarehouseKpiRepository,
  QuarantineWorkflowRepository, ThreeWayMatchRepository, AutoGlPostingRepository, PosEmployeeBalanceRepository,
} from './pos.module-imports';
// P4-TECHCARD-VARIANCE — texkarta-gate (WMS solishtirish mantig'i REUSE) + variance config.
import { PosTechCardGateService } from './application/services/pos-techcard-gate.service';
import { PosVarianceConfigService } from './application/services/pos-variance-config.service';
import { OutboundEnforcementService } from '../wms/application/outbound-enforcement.service';
import { CASH_REGISTER_REPO } from './domain/repositories/i-cash-register.repo';
import { POS_MOVEMENT_REPO } from './domain/repositories/i-pos-movement.repo';
import { POS_NOTIFICATIONS_REPO } from './domain/repositories/i-pos-notifications.repo';

@Module({
  imports: [CqrsModule],
  controllers: [
    ProcurementController,
    WarehouseConfigController,
    PosStubController,
    CashRegisterController,
    PosPrinterConfigV2Controller,
    MovementsController,
    ShiftHandoverController,
    BarcodeController,
    RequestsController,
    InventoryCountController,
    EmployeeController,
    ReportsController,
    MiniAppController,
    MiniAppHistoryController,
    PrinterConfigController,
    StockController,
    GlController,
    SyncController,
    PosNotificationsController,
    PosAnomaliesController,
    PosAuthController,
    InventoryPassportController,
    PosWmsController,
    WarehouseFeaturesController,
    PosOperationsController,
    WarehouseOpenController,
    StockIssuableController,
  ],
  providers: [
    { provide: POS_SVC_REPO, useClass: DrizzlePosSvcRepository },
    CashRegisterRepository,
    { provide: CASH_REGISTER_REPO, useExisting: CashRegisterRepository },
    CashRegisterService,
    PosService,
    PosMovementRepository,
    { provide: POS_MOVEMENT_REPO, useExisting: PosMovementRepository },
    // P4-TECHCARD-VARIANCE: WMS solishtirish servisini POS DI'ga REUSE qilamiz
    // (klass konstruktor-bog'liqliksiz; dublikat mantiq YO'Q) + POS wrapper + config.
    OutboundEnforcementService,
    PosTechCardGateService,
    PosVarianceConfigService,
    PosMovementService,
    PosMovementStatusRepository,
    PosMovementStatusService,
    PosMovementQueryService,
    PosShiftHandoverRepository,
    PosShiftHandoverService,
    ProcurementApprovalChainService,
    ProcurementRequestService,
    WarehouseConfigService,
    PosBarcodeRepository,
    PosBarcodeService,
    PosBarcodeExtRepository,
    PosBarcodeExtService,
    PosRequestRepository,
    PosRequestService,
    PosRequestExtRepository,
    PosRequestExtService,
    PosInventoryCountRepository,
    PosInventoryCountService,
    PosInventoryCountQueryRepository,
    PosInventoryCountQueryService,
    PosAuditRepository,
    PosAuditService,
    PosAuthRepository,
    PosAuthService,
    PosMovementQueryRepository,
    PosTelegramRepository,
    PosTelegramService,
    PosTelegramExtRepository,
    PosTelegramExtService,
    PosPdfRepository,
    PosPdfService,
    PosPdfInventoryRepository,
    PosPdfInventoryService,
    LabelRepository,
    LabelService,
    LabelExtService,
    PosLifecycleBlockRepository,
    LifecycleBlockService,
    PosStockReservationRepository,
    StockReservationService,
    EmployeeLedgerRepository,
    EmployeeLedgerService,
    EmployeeWriteOffRepository,
    EmployeeWriteOffService,
    PosEventHandler,
    PosSecondaryEventsHandler,
    PosEventRepository,
    PosDepartmentGuard,
    PosMiniAppRepository,
    PosMiniAppService,
    PosPrinterConfigRepository,
    PosPrinterConfigService,
    PosReportsRepository,
    PosReportsService,
    PosInventoryService,
    PosInventoryRepository,
    StockLedgerRepository,
    StockLedgerService,
    GlPostingLogRepository,
    GlPostingLogService,
    PosGlAutoService,
    PosBalanceGuardService,
    PosSyncRepository,
    PosSyncService,
    PosNotificationsRepository,
    { provide: POS_NOTIFICATIONS_REPO, useExisting: PosNotificationsRepository },
    PosNotificationsService,
    PosGateway,
    PosInventoryPassportRepository,
    PosInventoryPassportService,
    PosFifoService,
    PosLowStockJob,
    PosQuarantineCheckJob,
    PosFifoRecalculateJob,
    PosRequisitionWorkflowService,
    PosEmployeeBalanceService,
    PosWmsSyncService,
    PosWmsQueryService,
    // Wave 4 round-4 — completed listener removed 2026-06-06 (dead duplicate of inline path)
    PosWmsSyncCreatedListener,
    // P2-ANOMALY — qoida-asosli anomaliya aniqlash
    PosAnomalyRepository,
    PosAnomalyService,
    PosAnomalyListener,
    PosInactiveMaterialsJob,
    // Warehouse features — repositories (Sprint B)
    WarehouseEmployeesRepository,
    GoodsReceiptRepository,
    AutoBarcodeRepository,
    WarehouseKpiRepository,
    QuarantineWorkflowRepository,
    ThreeWayMatchRepository,
    AutoGlPostingRepository,
    PosEmployeeBalanceRepository,
    // POS Terminal — kirgach ombor AUTO-OPEN + etiket config (BE-T1-WAREHOUSE-OPEN)
    WarehouseOpenRepository,
    WarehouseOpenService,
    // POS Terminal — KIRIM barkod-gen + CHIQIM bron-blok (BE-T2-BARCODE-RESERV)
    PosStockIssuableRepository,
    PosStockIssuableService,
    // Warehouse features — services
    WarehouseEmployeesService,
    AutoBarcodeService,
    Material360Service,
    AutoGlPostingService,
    WarehouseKpiService,
    GoodsReceiptService,
    QuarantineWorkflowService,
    ThreeWayMatchService,
    SmsService,
    EmailService,
    TelegramBotService,
    QueueService,
  ],
  exports: [
    POS_SVC_REPO,
    PosService,
    PosMovementService,
    PosMovementStatusService,
    PosMovementQueryService,
    PosBarcodeService,
    PosBarcodeExtService,
    PosRequestService,
    PosRequestExtService,
    PosInventoryCountService,
    PosInventoryCountQueryService,
    EmployeeLedgerService,
    StockReservationService,
    PosAuditService,
    PosPdfService,
    PosPdfInventoryService,
    LabelService,
    LabelExtService,
    StockLedgerService,
    GlPostingLogService,
    PosNotificationsService,
    PosInventoryPassportService,
    PosFifoService,
    PosRequisitionWorkflowService,
    PosEmployeeBalanceService,
  ],
})
export class PosModule {}
