/**
 * @module mockup-components
 * @description Source module. See exports for details.
 */

// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {

};
