#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
#  EuroPrint ERP — Git Hook O'rnatuvchi
#  Ishlatish: bash scripts/setup-git-hooks.sh
# ════════════════════════════════════════════════════════════════════
set -euo pipefail

GRN='\033[0;32m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GIT_DIR="$(git rev-parse --show-toplevel)/.git"
HOOKS_DIR="$GIT_DIR/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
  echo -e "${RED}✗ .git/hooks papkasi topilmadi — bu git repo emasmi?${NC}"
  exit 1
fi

cat > "$HOOKS_DIR/pre-push" << 'HOOK_EOF'
#!/usr/bin/env bash
# EuroPrint ERP — Pre-Push CI Gate (auto-generated by setup-git-hooks.sh)
# Skip: git push --no-verify
SCRIPT="$(git rev-parse --show-toplevel)/scripts/run-all-reviewers.sh"

if [ ! -f "$SCRIPT" ]; then
  echo "⚠  Pre-push: reviewer skript topilmadi ($SCRIPT), skip qilinmoqda"
  exit 0
fi

echo ""
echo "=== EuroPrint ERP — Arxitektura CI tekshiruvi ==="
echo ""

bash "$SCRIPT" --quick
EXIT=$?

if [ $EXIT -ne 0 ]; then
  echo ""
  echo "=== Push bloklandi: reviewer(lar) FAIL. Xatolarni tuzating. ==="
  echo "    Majburan push: git push --no-verify"
  echo ""
  exit 1
fi

echo "=== Barcha reviewerlar PASS — push davom etmoqda ==="
exit 0
HOOK_EOF

chmod +x "$HOOKS_DIR/pre-push"

echo -e "${GRN}${BOLD}✅ Pre-push hook o'rnatildi: $HOOKS_DIR/pre-push${NC}"
echo ""
echo "  Har bir 'git push' oldidan barcha reviewerlar ishga tushadi."
echo "  Bypass: git push --no-verify"
echo ""
