// Uzbek -> Russian translation script for EuroPrint ERP
// Reads ru-placeholders.json and writes ru-translations.json
import fs from 'node:fs';
import path from 'node:path';

const INPUT = path.resolve('ru-placeholders.json');
const OUTPUT = path.resolve('ru-translations.json');

// ------- Helpers -------
// Normalize Uzbek apostrophes to a canonical form for matching
function norm(s) {
  return s
    .replace(/[''`‘’]/g, "'")
    .replace(/[`ʻʼʾ]/g, "'");
}

// Keywords/terms that must stay as-is (after stripping)
const KEEP_TOKENS = new Set([
  'BOM','MES','OEE','KPI','SKU','FIFO','FEFO','ROP','AQL','SPC','FMEA','RPN',
  'QC','HR','AI','CRM','ERP','WMS','PP','SD','MM','FI','CFO','JSON','API','URL',
  'ID','GRN','PIP','NPS','eNPS','RACI','OKR','LTV','ROI','ROAS','SEO','CMS','GPS',
  'IoT','MRO','MRP','GL','AP','AR','USD','EUR','UZS','SOS','PDF','SMS','SAP',
  'POS','IT','TG','VIP','GPT','MFA','OTP','JWT','CSV','XML','HTML','PNG','JPG',
  'CPU','RAM','RAID','SQL','XLSX','UI','UX','OK','PIN','QR','RFID','VPN'
]);

const BRANDS = new Set([
  'Adobe','Illustrator','Photoshop','InDesign','Telegram','Excel','Pantone',
  'EuroPrint','Europrint','Gemini','Vision','GPT','OpenAI','Claude','WhatsApp',
  'Google','Microsoft','Slack','Zoom','Notion','Jira','Asana','ClickUp',
  'Drizzle','PostgreSQL','React','NestJS','TypeScript','JavaScript','Node',
  'Linux','Windows','Mac','iOS','Android','GitHub','GitLab','Vite','Tailwind'
]);

// Detection helpers
function hasCyrillic(s) { return /[А-Яа-яЁё]/.test(s); }
function isExpression(s) {
  // TypeScript/JS-like
  return /[(){}=]|\|\||\?:|=>|\.length\b|\\u[0-9a-f]{4}/.test(s);
}
function isIdLike(s) {
  const t = s.trim();
  if (/\s/.test(t)) return false;
  if (/^[a-z][a-z0-9_-]*$/i.test(t) && t.length > 1) {
    // Things like 'material-id', 'vendor-001', 'EXTERNAL_IN', 'blocked_by_material'
    if (/[-_]/.test(t) || /^[A-Z][A-Z0-9_]+$/.test(t)) return true;
  }
  if (/^[A-Z][A-Z0-9_]+$/.test(t)) return true;
  if (/^[a-z]+-\d+$/i.test(t)) return true;
  return false;
}

// ------- Word-level dictionary (canonical lowercase with apostrophes as ') -------
// Maps Uzbek word -> Russian noun (nominative singular by default).
// For exact match of full strings, see PHRASE_MAP further down.
const WORD_MAP = new Map(Object.entries({
  // Particles, common verbs
  "yo'q": "нет",
  "yo'qotildi": "потеряно",
  "yo'qotilgan": "потерянный",
  "yo'qotish": "потеря",
  "ha": "да",
  "va": "и",
  "bilan": "с",
  "uchun": "для",
  "yoki": "или",
  "agar": "если",
  "lekin": "но",
  "ammo": "однако",
  "shuningdek": "также",
  "ham": "также",
  "har": "каждый",
  "barcha": "все",
  "barchasi": "все",
  "barchasini": "всех",
  "barchasiga": "всем",
  "hammasi": "все",
  "hammasini": "всё",
  "hech": "ничего",
  "qanday": "какой",
  "qaysi": "какой",
  "nima": "что",
  "kim": "кто",
  "qancha": "сколько",
  "necha": "сколько",
  "qachon": "когда",
  "qayer": "где",
  "qayerda": "где",
  "qayerga": "куда",
  "bu": "это",
  "ushbu": "данный",
  "shu": "этот",
  "u": "он",
  "ular": "они",
  "biz": "мы",
  "siz": "вы",
  "men": "я",
  "mening": "мой",
  "sizning": "ваш",
  "ularning": "их",
  "uning": "его",
  "haqida": "о",
  "orqali": "через",
  "ostida": "под",
  "ustida": "над",
  "ichida": "внутри",
  "tashqarida": "снаружи",
  "yonida": "рядом",
  "oldida": "перед",
  "keyin": "после",
  "oldin": "до",
  "avval": "до",
  "endi": "теперь",
  "hozir": "сейчас",
  "hozircha": "пока",
  "hozirgi": "текущий",
  "joriy": "текущий",
  "kelgusi": "будущий",
  "kelajak": "будущее",
  "o'tgan": "прошлый",
  "oxirgi": "последний",
  "so'nggi": "последний",
  "birinchi": "первый",
  "ikkinchi": "второй",
  "uchinchi": "третий",
  "oldingi": "предыдущий",
  "keyingi": "следующий",
  "yangi": "новый",
  "eski": "старый",
  "eng": "самый",
  "ko'p": "много",
  "kam": "мало",
  "ko'proq": "больше",
  "kamroq": "меньше",
  "yaxshi": "хорошо",
  "yomon": "плохо",
  "katta": "большой",
  "kichik": "маленький",
  "uzun": "длинный",
  "qisqa": "короткий",
  "tez": "быстро",
  "sekin": "медленно",
  "to'g'ri": "правильно",
  "noto'g'ri": "неправильно",
  "muhim": "важно",
  "kerak": "нужно",
  "mumkin": "можно",
  "emas": "нет",
  "bor": "есть",
  "yo'qmi": "нет?",
  "bormi": "есть?",
  "mavjud": "существует",
  "mavjudligi": "наличие",
  "topilmadi": "не найдено",
  "topildi": "найдено",
  "topilgan": "найденный",
  "saqlash": "сохранить",
  "saqlandi": "сохранено",
  "saqlanmoqda": "сохранение...",
  "yuklash": "загрузить",
  "yuklab": "загрузить",
  "yuklanmoqda": "загрузка...",
  "yuklandi": "загружено",
  "yuklangan": "загружено",
  "yuborish": "отправить",
  "yuborildi": "отправлено",
  "yuborilgan": "отправленный",
  "yuboruvchi": "отправитель",
  "qabul": "приём",
  "qabulchi": "получатель",
  "olish": "получить",
  "olindi": "получено",
  "olingan": "полученный",
  "berish": "выдать",
  "berildi": "выдано",
  "berilgan": "выданный",
  "qo'shish": "добавить",
  "qo'shildi": "добавлено",
  "qo'shilgan": "добавленный",
  "o'chirish": "удалить",
  "o'chirildi": "удалено",
  "o'chirilgan": "удалённый",
  "tahrirlash": "редактировать",
  "tahrirlandi": "отредактировано",
  "tahrirlangan": "отредактированный",
  "yaratish": "создать",
  "yaratildi": "создано",
  "yaratilgan": "созданный",
  "yaratilmoqda": "создание...",
  "tanlash": "выбрать",
  "tanlang": "выберите",
  "tanlandi": "выбрано",
  "tanlangan": "выбранный",
  "bekor": "отменить",
  "yopish": "закрыть",
  "yopildi": "закрыто",
  "ochish": "открыть",
  "ochildi": "открыто",
  "ochiq": "открытый",
  "yopiq": "закрытый",
  "chiqish": "выход",
  "kirish": "вход",
  "kirilmoqda": "вход...",
  "kiring": "войдите",
  "ko'rish": "посмотреть",
  "ko'rsatish": "показать",
  "ko'rsatilgan": "показанный",
  "yashirish": "скрыть",
  "ko'paytirish": "увеличить",
  "kamaytirish": "уменьшить",
  "topish": "найти",
  "qidirish": "поиск",
  "qidirilmoqda": "поиск...",
  "qidiring": "ищите",
  "filtr": "фильтр",
  "filter": "фильтр",
  "filtrlar": "фильтры",
  "filtrlash": "фильтрация",
  "saralash": "сортировка",
  "ortish": "увеличение",
  "kamayish": "уменьшение",
  "qayta": "пере",
  "qaytarish": "вернуть",
  "qaytarib": "обратно",
  "qaytdi": "вернулся",
  "qaytarib bo'lmaydi": "необратимо",

  // Time
  "yil": "год",
  "yillar": "годы",
  "oy": "месяц",
  "oylar": "месяцы",
  "kun": "день",
  "kunlar": "дни",
  "kunlik": "ежедневный",
  "soat": "час",
  "soatlar": "часы",
  "soatlik": "ежечасный",
  "daqiqa": "минута",
  "daqiqalar": "минуты",
  "soniya": "секунда",
  "hafta": "неделя",
  "haftalar": "недели",
  "haftalik": "еженедельный",
  "oylik": "ежемесячный",
  "yillik": "ежегодный",
  "bugun": "сегодня",
  "bugungi": "сегодняшний",
  "kecha": "вчера",
  "ertaga": "завтра",
  "vaqt": "время",
  "vaqti": "время",
  "muddat": "срок",
  "muddati": "срок",
  "sana": "дата",
  "sanasi": "дата",

  // Status / labels
  "holat": "статус",
  "holati": "статус",
  "holatlar": "статусы",
  "nom": "имя",
  "nomi": "название",
  "nomlar": "имена",
  "tur": "тип",
  "turi": "тип",
  "turlari": "типы",
  "kategoriya": "категория",
  "kategoriyasi": "категория",
  "guruh": "группа",
  "guruhi": "группа",
  "guruhlar": "группы",
  "ro'yxat": "список",
  "ro'yxati": "список",
  "ro'yxatlar": "списки",
  "jadval": "таблица",
  "jadvali": "таблица",
  "grafik": "график",
  "grafiklar": "графики",
  "chart": "диаграмма",
  "ma'lumot": "данные",
  "ma'lumotlar": "данные",
  "ma'lumotlari": "данные",
  "ma'lumotlarini": "данные",
  "ma'lumotlarni": "данные",
  "izoh": "комментарий",
  "izohi": "комментарий",
  "izohlar": "комментарии",
  "tavsif": "описание",
  "tavsifi": "описание",
  "sarlavha": "заголовок",
  "matn": "текст",
  "matni": "текст",
  "fayl": "файл",
  "fayli": "файл",
  "fayllar": "файлы",
  "faylni": "файл",
  "rasm": "изображение",
  "rasmlar": "изображения",
  "rasmi": "изображение",
  "qiymat": "значение",
  "qiymati": "значение",
  "qiymatlar": "значения",
  "raqam": "номер",
  "raqami": "номер",
  "soni": "количество",
  "miqdor": "количество",
  "miqdori": "количество",
  "narx": "цена",
  "narxi": "цена",
  "narxlar": "цены",
  "summa": "сумма",
  "summasi": "сумма",
  "valyuta": "валюта",
  "valyutasi": "валюта",
  "summa:": "Сумма:",
  "jami": "итого",
  "jami:": "Итого:",
  "umumiy": "общий",
  "o'rtacha": "среднее",
  "minimum": "минимум",
  "maksimum": "максимум",
  "min": "мин",
  "max": "макс",
  "foiz": "процент",
  "foizi": "процент",
  "ulush": "доля",
  "ulushi": "доля",
  "natija": "результат",
  "natijasi": "результат",
  "natijalar": "результаты",
  "natijalari": "результаты",

  // Business
  "buyurtma": "заказ",
  "buyurtmasi": "заказ",
  "buyurtmalar": "заказы",
  "mahsulot": "продукт",
  "mahsuloti": "продукт",
  "mahsulotlar": "продукты",
  "material": "материал",
  "materiali": "материал",
  "materiallar": "материалы",
  "mijoz": "клиент",
  "mijozi": "клиент",
  "mijozlar": "клиенты",
  "mijozni": "клиента",
  "mijozga": "клиенту",
  "yetkazib": "поставк",
  "yetkazib beruvchi": "поставщик",
  "ta'minotchi": "поставщик",
  "ta'minotchilar": "поставщики",
  "yetkazish": "доставка",
  "yetkazib berish": "доставка",
  "savdo": "продажи",
  "savdosi": "продажи",
  "sotuv": "продажа",
  "xarid": "закупка",
  "xaridor": "покупатель",
  "to'lov": "платёж",
  "to'lovi": "платёж",
  "to'lovlar": "платежи",
  "hisob": "счёт",
  "hisobi": "счёт",
  "hisoblar": "счета",
  "hisob-faktura": "счёт-фактура",
  "faktura": "счёт",
  "shartnoma": "договор",
  "shartnomasi": "договор",
  "shartnomalar": "договоры",
  "kelishuv": "соглашение",
  "lavozim": "должность",
  "lavozimi": "должность",
  "lavozimlar": "должности",
  "xodim": "сотрудник",
  "xodimi": "сотрудник",
  "xodimlar": "сотрудники",
  "xodimni": "сотрудника",
  "xodimga": "сотруднику",
  "xodimning": "сотрудника",
  "xodimlarni": "сотрудников",
  "xodimlarning": "сотрудников",
  "ishchi": "рабочий",
  "ishchilar": "рабочие",
  "menejer": "менеджер",
  "direktor": "директор",
  "rahbar": "руководитель",
  "mas'ul": "ответственный",
  "mas'uli": "ответственный",
  "mutaxassis": "специалист",
  "bo'lim": "отдел",
  "bo'limi": "отдел",
  "bo'limlar": "отделы",
  "bo'limni": "отдел",
  "tashkilot": "организация",
  "kompaniya": "компания",
  "kompaniyasi": "компания",
  "kompaniyani": "компанию",
  "kompaniyaga": "компании",
  "korxona": "предприятие",
  "filial": "филиал",
  "ofis": "офис",
  "sex": "цех",
  "sexlar": "цеха",
  "ish": "работа",
  "ishi": "работа",
  "ishlar": "работы",
  "ishga": "на работу",
  "ishlab": "производ",
  "ishlab chiqarish": "производство",
  "ishlab chiqarilgan": "произведённый",
  "ishlash": "работать",
  "ishlamoqda": "работает",
  "ishladi": "работал",
  "ishlamadi": "не работал",
  "yangi": "новый",
  "tayinlash": "назначить",
  "tayinlandi": "назначено",
  "tayinlangan": "назначенный",
  "tayinlanmagan": "не назначен",
  "tayinlang": "назначьте",
  "maosh": "зарплата",
  "maoshi": "зарплата",
  "bonus": "бонус",
  "mukofot": "премия",
  "mukofoti": "премия",
  "jarima": "штраф",
  "jarimasi": "штраф",
  "ta'til": "отпуск",
  "ta'tili": "отпуск",
  "kasallik": "больничный",
  "davomad": "посещаемость",
  "davomadi": "посещаемость",
  "ish vaqti": "рабочее время",
  "ish kuni": "рабочий день",
  "ish haqi": "зарплата",

  // Forms
  "majburiy": "обязательно",
  "ixtiyoriy": "необязательно",
  "asosiy": "основной",
  "qo'shimcha": "дополнительный",
  "yordamchi": "вспомогательный",
  "boshqa": "другой",
  "umumiy": "общий",
  "xususiy": "частный",
  "shaxsiy": "личный",
  "rasmiy": "официальный",
  "norasmiy": "неофициальный",
  "tasdiqlash": "подтвердить",
  "tasdiqlandi": "подтверждено",
  "tasdiqlangan": "подтверждённый",
  "tasdiqlaysizmi": "подтверждаете?",
  "rad": "отклонить",
  "rad etish": "отклонить",
  "rad etildi": "отклонено",
  "rad etilgan": "отклонённый",
  "rad etilmagan": "не отклонённый",
  "qabul qilish": "принять",
  "qabul qilindi": "принято",
  "qabul qilingan": "принятый",
  "kutish": "ожидание",
  "kutilmoqda": "ожидается",
  "kutilayotgan": "ожидаемый",
  "kutayotgan": "ожидающий",
  "bekor qilish": "отменить",
  "bekor qilindi": "отменено",
  "bekor qilingan": "отменённый",
  "tugatish": "завершить",
  "tugatildi": "завершено",
  "tugatilgan": "завершённый",
  "tugadi": "завершён",
  "boshlash": "начать",
  "boshlandi": "начато",
  "boshlangan": "начатый",
  "boshlanish": "начало",
  "boshlanishi": "начало",
  "tugash": "окончание",
  "tugashi": "окончание",
  "davom": "продолжить",
  "davom ettirish": "продолжить",
  "davomi": "продолжение",
  "to'xtatish": "остановить",
  "to'xtash": "остановка",
  "to'xtatildi": "остановлено",
  "to'xtatilgan": "остановленный",
  "pauza": "пауза",
  "to'liq": "полный",
  "to'liqligi": "полнота",
  "qisman": "частичный",
  "bo'sh": "пустой",
  "to'la": "полный",

  // KPI/Status
  "faol": "активный",
  "faolligi": "активность",
  "aktiv": "активный",
  "nofaol": "неактивный",
  "passiv": "пассивный",
  "tugallangan": "выполненный",
  "bajarilgan": "выполнено",
  "bajarilmagan": "не выполнено",
  "bajarish": "выполнить",
  "bajarildi": "выполнено",
  "bajarilmoqda": "выполняется",
  "rejalashtirilgan": "запланированный",
  "rejalashtirish": "планирование",
  "reja": "план",
  "rejasi": "план",
  "darajada": "на уровне",
  "daraja": "уровень",
  "darajasi": "уровень",
  "daraja:": "Уровень:",
  "ball": "балл",
  "balli": "балл",
  "ko'rsatkich": "показатель",
  "ko'rsatkichi": "показатель",
  "ko'rsatkichlar": "показатели",
  "ko'rsatkichlari": "показатели",
  "samaradorlik": "эффективность",
  "samaradorligi": "эффективность",
  "unumdorlik": "производительность",
  "unumdorligi": "производительность",
  "sifat": "качество",
  "sifati": "качество",
  "tahlil": "анализ",
  "tahlili": "анализ",
  "tahlillar": "анализы",
  "hisobot": "отчёт",
  "hisoboti": "отчёт",
  "hisobotlar": "отчёты",
  "statistika": "статистика",
  "statistikasi": "статистика",
  "prognoz": "прогноз",
  "prognozi": "прогноз",
  "prognozlar": "прогнозы",
  "byudjet": "бюджет",
  "byudjeti": "бюджет",
  "xarajat": "расход",
  "xarajati": "расход",
  "xarajatlar": "расходы",
  "daromad": "доход",
  "daromadi": "доход",
  "foyda": "прибыль",
  "foydasi": "прибыль",
  "zarar": "убыток",
  "zarari": "убыток",

  // Common UI
  "sahifa": "страница",
  "sahifasi": "страница",
  "sahifalar": "страницы",
  "menyu": "меню",
  "menyusi": "меню",
  "tugma": "кнопка",
  "tugmasi": "кнопка",
  "tugmalar": "кнопки",
  "oyna": "окно",
  "oynasi": "окно",
  "shakl": "форма",
  "shakli": "форма",
  "maydon": "поле",
  "maydoni": "поле",
  "maydonlar": "поля",
  "qator": "строка",
  "qatori": "строка",
  "qatorlar": "строки",
  "ustun": "колонка",
  "ustuni": "колонка",
  "ustunlar": "колонки",
  "yacheyka": "ячейка",
  "rasm": "изображение",
  "rasmlar": "изображения",
  "ikon": "иконка",
  "ikonka": "иконка",
  "rang": "цвет",
  "rangi": "цвет",
  "ranglar": "цвета",
  "o'lcham": "размер",
  "o'lchami": "размер",
  "o'lchov": "единица измерения",
  "o'lchovi": "единица измерения",
  "kichik": "маленький",
  "katta": "большой",
  "o'rta": "средний",
  "o'rtacha": "средний",
  "balandlik": "высота",
  "kenglik": "ширина",
  "uzunlik": "длина",
  "chuqurlik": "глубина",

  // Printing-specific
  "bosma": "печать",
  "bosish": "печатать",
  "bosildi": "напечатано",
  "bosib chiqarish": "распечатать",
  "tirajalar": "тиражи",
  "tiraj": "тираж",
  "tiraji": "тираж",
  "shtampovkalar": "штамповки",
  "shtampovka": "штамповка",
  "matbaa": "типография",
  "rulon": "рулон",
  "rulo": "рулон",
  "karton": "картон",
  "qog'oz": "бумага",
  "qog'ozi": "бумага",
  "konvert": "конверт",
  "stiker": "стикер",
  "yorliq": "этикетка",
  "yorlig'i": "этикетка",
  "yorliqlar": "этикетки",
  "bo'yoq": "краска",
  "bo'yoqlar": "краски",
  "siyoh": "чернила",
  "kesish": "резка",
  "qirqish": "обрезка",
  "yelimlash": "склейка",
  "tikish": "сшивка",
  "lak": "лак",
  "ofset": "офсет",
  "fleksografiya": "флексография",
  "raqamli": "цифровой",
  "rangli": "цветной",
  "qora-oq": "чёрно-белый",
  "format": "формат",
  "formati": "формат",
  "dizayn": "дизайн",
  "dizayni": "дизайн",
  "maket": "макет",
  "maketi": "макет",
  "tip": "тип",
  "tipo": "тип",

  // Quality/Production
  "defekt": "дефект",
  "defekti": "дефект",
  "defektlar": "дефекты",
  "brak": "брак",
  "qayta ishlov": "переработка",
  "tekshirish": "проверка",
  "tekshiruv": "проверка",
  "tekshirildi": "проверено",
  "sertifikat": "сертификат",
  "sertifikati": "сертификат",
  "standart": "стандарт",
  "standarti": "стандарт",
  "talab": "требование",
  "talabi": "требование",
  "talablar": "требования",
  "namuna": "образец",
  "namunasi": "образец",
  "namunalar": "образцы",
  "sinov": "тест",
  "sinovi": "тест",
  "sinovlar": "тесты",
  "test": "тест",
  "testi": "тест",
  "testlar": "тесты",
  "natija": "результат",

  // Warehouse
  "ombor": "склад",
  "ombori": "склад",
  "omborlar": "склады",
  "skladi": "склад",
  "qoldiq": "остаток",
  "qoldig'i": "остаток",
  "qoldiqlar": "остатки",
  "inventar": "инвентарь",
  "inventarizatsiya": "инвентаризация",
  "kelib tushish": "поступление",
  "chiqim": "расход",
  "kirim": "приход",
  "harakat": "движение",
  "harakatlar": "движения",
  "harakati": "движение",

  // HR
  "ariza": "заявление",
  "arizasi": "заявление",
  "arizalar": "заявления",
  "ishga olish": "приём на работу",
  "ishdan bo'shatish": "увольнение",
  "nomzod": "кандидат",
  "nomzodi": "кандидат",
  "nomzodlar": "кандидаты",
  "intervyu": "собеседование",
  "intervyusi": "собеседование",
  "rekruting": "рекрутинг",
  "adaptatsiya": "адаптация",
  "ta'lim": "образование",
  "ta'limi": "образование",
  "kurs": "курс",
  "kursi": "курс",
  "kurslar": "курсы",
  "modul": "модуль",
  "moduli": "модуль",
  "modullar": "модули",
  "dars": "урок",
  "darsi": "урок",
  "darslar": "уроки",
  "savol": "вопрос",
  "savoli": "вопрос",
  "savollar": "вопросы",
  "javob": "ответ",
  "javobi": "ответ",
  "javoblar": "ответы",
  "imtihon": "экзамен",
  "imtihoni": "экзамен",
  "sertifikatsiya": "сертификация",
  "ko'nikma": "навык",
  "ko'nikmasi": "навык",
  "ko'nikmalar": "навыки",
  "bilim": "знание",
  "bilimi": "знание",
  "tajriba": "опыт",
  "tajribasi": "опыт",

  // CRM
  "lid": "лид",
  "lidi": "лид",
  "lidlar": "лиды",
  "lead": "лид",
  "sotish": "продажа",
  "voronka": "воронка",
  "pipeline": "воронка",
  "bosqich": "этап",
  "bosqichi": "этап",
  "bosqichlar": "этапы",
  "deal": "сделка",
  "deals": "сделки",
  "marketing": "маркетинг",
  "reklama": "реклама",
  "kampaniya": "кампания",
  "kampaniyasi": "кампания",
  "kanal": "канал",
  "kanali": "канал",
  "kanallar": "каналы",

  // Misc commonly seen
  "manzil": "адрес",
  "manzili": "адрес",
  "telefon": "телефон",
  "telefoni": "телефон",
  "telefonlar": "телефоны",
  "email": "email",
  "pochta": "почта",
  "ism": "имя",
  "ismi": "имя",
  "familiya": "фамилия",
  "familiyasi": "фамилия",
  "to'liq ism": "полное имя",
  "yoshi": "возраст",
  "yosh": "возраст",
  "jinsi": "пол",
  "erkak": "мужской",
  "ayol": "женский",
  "oilaviy": "семейный",
  "oilaviy holat": "семейное положение",
  "tug'ilgan sana": "дата рождения",
  "tug'ilgan": "родился",
  "farzand": "ребёнок",
  "farzandlar": "дети",
  "farzandlar soni": "количество детей",
  "uy": "дом",
  "ijara": "аренда",
  "shaxsiy uy": "собственный дом",

  // Chat / messaging
  "chat": "чат",
  "chati": "чат",
  "chatlar": "чаты",
  "xabar": "сообщение",
  "xabari": "сообщение",
  "xabarlar": "сообщения",
  "xabarni": "сообщение",
  "xabarlarda": "в сообщениях",
  "suhbat": "беседа",
  "suhbati": "беседа",
  "suhbatlar": "беседы",
  "xona": "комната",
  "xonasi": "комната",
  "xonalar": "комнаты",
  "guruh": "группа",
  "kanal": "канал",
  "a'zo": "участник",
  "a'zolar": "участники",
  "egasi": "владелец",
  "yozish": "написать",
  "yozildi": "написано",
  "yozayotgan": "печатает",
  "yozing": "напишите",
  "online": "онлайн",
  "offline": "офлайн",
  "ulanmoqda": "подключение...",
  "ulandi": "подключено",
  "ulanish": "подключение",
  "ulanmagan": "не подключён",

  // Misc actions
  "ko'chirish": "переместить",
  "nusxalash": "копировать",
  "ulashish": "поделиться",
  "ulashing": "поделитесь",
  "yuklab olish": "скачать",
  "eksport": "экспорт",
  "import": "импорт",
  "chop etish": "распечатать",
  "yangilash": "обновить",
  "yangilanmoqda": "обновляется...",
  "yangilandi": "обновлено",
  "yangilangan": "обновлённый",
  "yaratishingiz": "создать",

  // Misc nouns
  "kategoriya": "категория",
  "kategoriyalar": "категории",
  "papka": "папка",
  "papkasi": "папка",
  "papkalar": "папки",
  "amal": "действие",
  "amali": "действие",
  "amallar": "действия",
  "amalni": "действие",
  "harakat": "действие",
  "harakatlar": "действия",
  "voqea": "событие",
  "voqealar": "события",
  "hodisa": "событие",
  "hodisalar": "события",
  "tadbir": "мероприятие",
  "tadbirlar": "мероприятия",
  "uchrashuv": "встреча",
  "uchrashuvi": "встреча",
  "qo'ng'iroq": "звонок",
  "qo'ng'irog'i": "звонок",
  "qo'ng'iroqlar": "звонки",
  "tarix": "история",
  "tarixi": "история",
  "log": "журнал",
  "loglar": "логи",
  "audit": "аудит",
  "auditi": "аудит",

  // Common Uzbek text fragments
  "ta": "шт.",
  "dona": "шт.",
  "ushbu": "данный",
  "shu": "этот",
  "qaytarib bo'lmaydi": "необратимо",
  "tasdiqlash kerakmi": "подтвердить?",
  "amalni qaytarib bo'lmaydi": "это действие нельзя отменить",

  // Misc
  "tahdid": "угроза",
  "xavf": "риск",
  "xavfi": "риск",
  "xavfli": "опасный",
  "muammo": "проблема",
  "muammosi": "проблема",
  "muammolar": "проблемы",
  "ogohlantirish": "предупреждение",
  "ogohlantirishlar": "предупреждения",
  "bildirishnoma": "уведомление",
  "bildirishnomalar": "уведомления",
  "xatolik": "ошибка",
  "xato": "ошибка",
  "xatosi": "ошибка",
  "xatolar": "ошибки",
  "muvaffaqiyat": "успех",
  "muvaffaqiyatli": "успешно",
  "muvaffaqiyatsiz": "неудачно",
  "tugadi": "завершено",
  "tayyor": "готов",
  "tayyorlik": "готовность",
  "tayyorlanmoqda": "подготавливается...",
  "ulanish yo'q": "нет соединения",

  // Sentence-level helpers
  "kiriting": "введите",
  "kiritildi": "введено",
  "kiritilgan": "введённый",
  "tanlanmagan": "не выбрано",
  "tanlang...": "выберите...",
  "yozing...": "напишите...",
  "qidiring...": "ищите...",
}));

// ------- Phrase-level dictionary (whole-string match, normalized lowercase apostrophe) -------
// Trumps WORD_MAP if matched exactly.
const PHRASE_MAP = new Map();

function addPhrase(uz, ru) {
  PHRASE_MAP.set(norm(uz).toLowerCase(), ru);
}

// Add many common UI phrases
[
  ["O'zbekcha", "Узбекский"],
  ["Rus tili", "Русский"],
  ["Ingliz tili", "Английский"],
  ["Saqlash", "Сохранить"],
  ["Bekor qilish", "Отмена"],
  ["Yopish", "Закрыть"],
  ["Ochish", "Открыть"],
  ["O'chirish", "Удалить"],
  ["Tahrirlash", "Редактировать"],
  ["Yaratish", "Создать"],
  ["Qo'shish", "Добавить"],
  ["Tanlash", "Выбрать"],
  ["Tasdiqlash", "Подтвердить"],
  ["Davom etish", "Продолжить"],
  ["Orqaga", "Назад"],
  ["Keyingisi", "Далее"],
  ["Tayyor", "Готово"],
  ["Yuklash", "Загрузить"],
  ["Yuklab olish", "Скачать"],
  ["Yangilash", "Обновить"],
  ["Qidirish", "Поиск"],
  ["Filtr", "Фильтр"],
  ["Saralash", "Сортировка"],
  ["Eksport", "Экспорт"],
  ["Import", "Импорт"],
  ["Chop etish", "Печать"],
  ["Yuborish", "Отправить"],
  ["Qabul qilish", "Принять"],
  ["Rad etish", "Отклонить"],
  ["Tozalash", "Очистить"],
  ["Hammasini tozalash", "Очистить всё"],
  ["Hammasini tanlash", "Выбрать всё"],
  ["Barchasini tanlash", "Выбрать всё"],
  ["Barchasini o'chirish", "Удалить всё"],
  ["Yuklanmoqda...", "Загрузка..."],
  ["Saqlanmoqda...", "Сохранение..."],
  ["Yaratilmoqda...", "Создание..."],
  ["Qidirilmoqda...", "Поиск..."],
  ["Yuborilmoqda...", "Отправка..."],
  ["Ulanmoqda...", "Подключение..."],
  ["Yuklanmoqda", "Загрузка"],
  ["Ma'lumotlar yuklanmoqda", "Загрузка данных"],
  ["Ma'lumotlar yuklanmoqda...", "Загрузка данных..."],
  ["Kirilmoqda...", "Вход..."],
  ["Hisoblanyapti...", "Расчёт..."],
  ["Qayta hisoblash", "Пересчитать"],
  ["Qayta urinish", "Повторить"],
  ["Qayta yuklash", "Перезагрузить"],
  ["Qayta yuborish", "Повторно отправить"],
  ["Topilmadi", "Не найдено"],
  ["Natijalar topilmadi", "Результаты не найдены"],
  ["Hech narsa topilmadi", "Ничего не найдено"],
  ["Ma'lumot yo'q", "Нет данных"],
  ["Ma'lumotlar yo'q", "Нет данных"],
  ["Hozircha ma'lumot yo'q", "Пока нет данных"],
  ["Mavjud emas", "Недоступно"],
  ["Hali mavjud emas", "Пока недоступно"],
  ["Bo'sh", "Пусто"],
  ["Bo'sh ro'yxat", "Пустой список"],
  ["Yangi yaratish", "Создать новый"],
  ["Yangi qo'shish", "Добавить новый"],
  ["Batafsil", "Подробнее"],
  ["Batafsil ma'lumot", "Подробная информация"],
  ["Ko'rsatish", "Показать"],
  ["Yashirish", "Скрыть"],
  ["Holat", "Статус"],
  ["Holati", "Статус"],
  ["Aktiv", "Активный"],
  ["Faol", "Активный"],
  ["Nofaol", "Неактивный"],
  ["Yangi", "Новый"],
  ["Eski", "Старый"],
  ["Kutilmoqda", "Ожидается"],
  ["Kutilayotgan", "Ожидается"],
  ["Kutishda", "В ожидании"],
  ["Tasdiqlangan", "Подтверждено"],
  ["Tasdiqlanmagan", "Не подтверждено"],
  ["Rad etilgan", "Отклонено"],
  ["Tugatilgan", "Завершено"],
  ["Bajarilgan", "Выполнено"],
  ["Bajarilmagan", "Не выполнено"],
  ["Yopilgan", "Закрыто"],
  ["Ochiq", "Открыто"],

  // Common questions
  ["Tasdiqlaysizmi?", "Подтверждаете?"],
  ["O'chirishni tasdiqlaysizmi?", "Подтвердить удаление?"],
  ["Bu amalni qaytarib bo'lmaydi.", "Это действие нельзя отменить."],
  ["Bu amalni qaytarib bo'lmaydi", "Это действие нельзя отменить"],
  ["O'chirishni xohlaysizmi?", "Хотите удалить?"],

  // Login / system
  ["Tizimga kirish", "Вход в систему"],
  ["Tizimga kirish sahifasi", "Страница входа в систему"],
  ["Tizimdan chiqish", "Выход из системы"],
  ["EuroPrint ERP", "EuroPrint ERP"],
  ["EuroPrint ERP ga xush kelibsiz", "Добро пожаловать в EuroPrint ERP"],
  ["ERP ga qaytish", "Вернуться в ERP"],
  ["← ERP ga qaytish", "← Вернуться в ERP"],
  ["Bosh sahifa", "Главная"],
  ["Asosiy sahifa", "Главная страница"],
  ["Sozlamalar", "Настройки"],
  ["Profil", "Профиль"],
  ["Chiqish", "Выход"],

  // Direction labels
  ["ID", "ID"],
  ["Email", "Email"],
  ["Email manzil", "Email адрес"],
  ["Email manzili", "Email адрес"],
  ["Telefon", "Телефон"],
  ["Telefon raqami", "Номер телефона"],
  ["Manzil", "Адрес"],
  ["Ism", "Имя"],
  ["Ism *", "Имя *"],
  ["Familiya", "Фамилия"],
  ["Familiya *", "Фамилия *"],
  ["Otasining ismi", "Отчество"],
  ["To'liq ism", "Полное имя"],
  ["Ismi-sharifi", "Ф.И.О."],
  ["Ismi sharifi", "Ф.И.О."],
  ["Parol", "Пароль"],
  ["Parolni unutdingizmi?", "Забыли пароль?"],
  ["Parolni tasdiqlash", "Подтверждение пароля"],
  ["Yangi parol", "Новый пароль"],
  ["Foydalanuvchi", "Пользователь"],
  ["Foydalanuvchi nomi", "Имя пользователя"],
  ["Foydalanuvchilar", "Пользователи"],
  ["Login", "Логин"],

  // Common operations text
  ["Saqlash va davom etish", "Сохранить и продолжить"],
  ["Bekor qilish va chiqish", "Отменить и выйти"],
  ["Filtrni saqlash", "Сохранить фильтр"],
  ["Filtrlarni tozalash", "Очистить фильтры"],
  ["Barcha filtrlar", "Все фильтры"],
  ["Kengaytirilgan filtrlar", "Расширенные фильтры"],

  // Time/Date headers
  ["Sana", "Дата"],
  ["Sanasi", "Дата"],
  ["Vaqt", "Время"],
  ["Vaqti", "Время"],
  ["Muddat", "Срок"],
  ["Muddati", "Срок"],
  ["Boshlanish sanasi", "Дата начала"],
  ["Tugash sanasi", "Дата окончания"],
  ["Yopilish sanasi", "Дата закрытия"],
  ["Yaratilgan sana", "Дата создания"],
  ["Yaratilgan", "Создано"],
  ["O'zgartirilgan", "Изменено"],
  ["O'zgartirilgan sana", "Дата изменения"],

  // Yes/no
  ["Ha", "Да"],
  ["Yo'q", "Нет"],
  ["Mumkin", "Можно"],
  ["Mumkin emas", "Нельзя"],
  ["Erkak", "Мужской"],
  ["Ayol", "Женский"],

  // Time periods
  ["Bugun", "Сегодня"],
  ["Kecha", "Вчера"],
  ["Ertaga", "Завтра"],
  ["Bu hafta", "На этой неделе"],
  ["Bu oy", "В этом месяце"],
  ["Bu yil", "В этом году"],
  ["O'tgan hafta", "На прошлой неделе"],
  ["O'tgan oy", "В прошлом месяце"],
  ["O'tgan yil", "В прошлом году"],
  ["Keyingi hafta", "На следующей неделе"],
  ["Keyingi oy", "В следующем месяце"],
  ["Joriy hafta", "Текущая неделя"],
  ["Joriy oy", "Текущий месяц"],
  ["Joriy yil", "Текущий год"],
  ["Hozir", "Сейчас"],
  ["Hozircha", "Пока"],
  ["Avval", "Ранее"],
  ["Keyin", "Позже"],

  // Numbers / units
  ["dona", "шт."],
  ["ta", "шт."],
  ["kg", "кг"],
  ["g", "г"],
  ["l", "л"],
  ["ml", "мл"],
  ["m", "м"],
  ["mm", "мм"],
  ["cm", "см"],
  ["m²", "м²"],
  ["m³", "м³"],

  // Currency
  ["UZS", "UZS"],
  ["so'm", "сум"],
  ["USD", "USD"],
  ["EUR", "EUR"],

  // Confirmation patterns
  ["O'chirish", "Удалить"],
  ["O'chirilsinmi?", "Удалить?"],
  ["O'chirildi", "Удалено"],

  // Tashabbus / KPI
  ["Daraja", "Уровень"],
  ["Ball", "Балл"],
  ["Bonus to'lovlar", "Бонусные выплаты"],

  // Status badges (printing-specific)
  ["Yangi", "Новый"],
  ["Bajarilmoqda", "В процессе"],
  ["Yakunlandi", "Завершено"],
  ["Yakuniy", "Финальный"],
  ["Tasdiqlash kutilmoqda", "Ожидает подтверждения"],
  ["To'lov kutilmoqda", "Ожидает оплаты"],
  ["To'langan", "Оплачено"],
  ["To'lanmagan", "Не оплачено"],

  // Reports
  ["Hisobot", "Отчёт"],
  ["Hisobotlar", "Отчёты"],
  ["Tahlil", "Анализ"],
  ["Tahlillar", "Анализы"],
  ["Statistika", "Статистика"],
  ["Statistikasi", "Статистика"],
  ["Grafik", "График"],
  ["Jadval", "Таблица"],
  ["Diagramma", "Диаграмма"],

  // Misc commonly used short labels
  ["Tur", "Тип"],
  ["Turi", "Тип"],
  ["Nom", "Название"],
  ["Nomi", "Название"],
  ["Tavsif", "Описание"],
  ["Tavsifi", "Описание"],
  ["Izoh", "Комментарий"],
  ["Izohlar", "Комментарии"],
  ["Izohlar yo'q", "Нет комментариев"],
  ["Tarix yo'q", "История пуста"],
  ["Soha", "Сфера"],

  // Charts/empty states
  ["Hozircha faoliyatlar yo'q", "Пока нет активностей"],
  ["Xabarlar yo'q", "Нет сообщений"],
  ["Chatlar yo'q", "Нет чатов"],
  ["Fayllar yo'q", "Нет файлов"],
  ["A'zolar yo'q", "Нет участников"],
  ["Xona topilmadi", "Комната не найдена"],
  ["Birinchi xabarni yuboring!", "Отправьте первое сообщение!"],
  ["Pinlangan", "Закреплено"],
  ["Pinlangan xabar", "Закреплённое сообщение"],
  ["Pinlangan xabarlar", "Закреплённые сообщения"],
  ["Pinlangan xabarlar yo'q", "Нет закреплённых сообщений"],
  ["Pin olib tashlash", "Открепить"],

  // Common 1-2 word labels
  ["Hammasi", "Все"],
  ["Barchasi", "Все"],
  ["Boshqa", "Другое"],
  ["Boshqalar", "Другие"],
  ["Anonim", "Анонимный"],
  ["Egasi", "Владелец"],
  ["A'zolar", "Участники"],
  ["Online", "Онлайн"],
  ["Offline", "Офлайн"],
  ["Yozayotgan", "Печатает"],

  ["Daraja", "Уровень"],
  ["Daraja:", "Уровень:"],
  ["Ball", "Балл"],
  ["Mukofot", "Премия"],
  ["Jazo", "Штраф"],

  // Days of week
  ["Dushanba", "Понедельник"],
  ["Seshanba", "Вторник"],
  ["Chorshanba", "Среда"],
  ["Payshanba", "Четверг"],
  ["Juma", "Пятница"],
  ["Shanba", "Суббота"],
  ["Yakshanba", "Воскресенье"],

  // Months
  ["Yanvar", "Январь"],
  ["Fevral", "Февраль"],
  ["Mart", "Март"],
  ["Aprel", "Апрель"],
  ["May", "Май"],
  ["Iyun", "Июнь"],
  ["Iyul", "Июль"],
  ["Avgust", "Август"],
  ["Sentabr", "Сентябрь"],
  ["Oktabr", "Октябрь"],
  ["Noyabr", "Ноябрь"],
  ["Dekabr", "Декабрь"],
].forEach(([uz, ru]) => addPhrase(uz, ru));

// ------- The translator -------
function fixCase(translated, original) {
  // If original is fully uppercase, uppercase translation
  if (original === original.toUpperCase() && /[A-Z]/.test(original)) {
    // Probably acronym; skip
  }
  // If original starts uppercase, ensure translation starts uppercase
  if (/^[A-ZА-ЯЁ]/.test(original.trim()) && /^[а-яё]/.test(translated)) {
    return translated.charAt(0).toUpperCase() + translated.slice(1);
  }
  return translated;
}

function translateWord(w) {
  if (!w) return w;
  // Strip surrounding punctuation
  const m = w.match(/^([^A-Za-zА-Яа-яЁё0-9'']*)([\s\S]*?)([^A-Za-zА-Яа-яЁё0-9'']*)$/);
  const pre = m ? m[1] : '';
  const core = m ? m[2] : w;
  const post = m ? m[3] : '';
  if (!core) return w;

  // Preserved tokens
  if (KEEP_TOKENS.has(core) || KEEP_TOKENS.has(core.toUpperCase())) return pre + core + post;
  if (BRANDS.has(core) || [...BRANDS].some(b => b.toLowerCase() === core.toLowerCase())) return pre + core + post;

  // Number or numeric+unit
  if (/^\d+$/.test(core)) return pre + core + post;
  if (/^\d+[%]?$/.test(core)) return pre + core + post;

  // Already Russian
  if (hasCyrillic(core)) return pre + core + post;

  const lower = core.toLowerCase();
  const normLower = norm(lower);

  const hit = WORD_MAP.get(normLower);
  if (hit) {
    // Preserve initial capital
    let out = hit;
    if (/^[A-ZА-ЯЁ]/.test(core)) {
      out = out.charAt(0).toUpperCase() + out.slice(1);
    }
    return pre + out + post;
  }

  return pre + core + post;
}

function translateString(orig) {
  const original = orig;
  if (!original) return original;

  // Skip rules
  if (hasCyrillic(original)) return original;
  if (isExpression(original)) return original;
  if (isIdLike(original)) return original;

  // Phrase-level exact match (lowercase, normalized apostrophe)
  const phraseKey = norm(original).toLowerCase().trim();
  const phraseHit = PHRASE_MAP.get(phraseKey);
  if (phraseHit) {
    return phraseHit;
  }

  // Also try without trailing punctuation
  const m = original.match(/^([\s\S]*?)([\s\.\,\!\?\:\;\…\*•]+)$/);
  if (m) {
    const baseKey = norm(m[1]).toLowerCase().trim();
    const baseHit = PHRASE_MAP.get(baseKey);
    if (baseHit) {
      return baseHit + m[2];
    }
  }

  // Word-by-word fallback. Preserve emojis and existing latin tokens.
  // Split keeping whitespace and punctuation positions.
  const tokens = original.split(/(\s+|[.,!?:;\(\)\[\]•—–…"]|—|–|…|\*)/);
  let translated = tokens.map(t => {
    if (!t) return t;
    if (/^\s+$/.test(t)) return t;
    if (/^[.,!?:;\(\)\[\]•—–…"\*—–…]+$/.test(t)) return t;
    // Emoji etc?
    if (/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(t)) return t;
    // Numbers
    if (/^\d/.test(t)) return t;
    return translateWord(t);
  }).join('');

  return translated;
}

// ------- Main -------
const data = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

const out = {};
let stats = { total: 0, alreadyRu: 0, codeLike: 0, idLike: 0, phraseHit: 0, wordTranslated: 0, untouched: 0 };

for (const entry of data) {
  stats.total++;
  const k = entry.k;
  const v = entry.v;

  if (hasCyrillic(v)) {
    out[k] = v;
    stats.alreadyRu++;
    continue;
  }
  if (isExpression(v)) {
    out[k] = v;
    stats.codeLike++;
    continue;
  }
  if (isIdLike(v)) {
    out[k] = v;
    stats.idLike++;
    continue;
  }

  const translated = translateString(v);
  out[k] = translated;
  if (translated === v) stats.untouched++;
  else stats.wordTranslated++;
}

fs.writeFileSync(OUTPUT, JSON.stringify(out, null, 2), 'utf8');
console.log('Stats:', stats);
console.log('Output written to', OUTPUT);
