/**
 * @module kanban-schema
 * @description Re-export shim. Canonical definitions live in ./kanban/kanban-core and
 * ./kanban/kanban-extended. This file is kept so that any legacy import of
 * "./kanban-schema" continues to resolve remaining table symbols unchanged.
 * NOTE: `kanbanBoards`/`kanbanColumns` removed 2026-07-02 — orphan in lib/db.
 */

export {
  kanbanCards,
  insertKanbanCardSchema,
  kanbanComments,
  insertKanbanCommentSchema,
} from "./kanban/kanban-core";

export type {
  KanbanCard,
  InsertKanbanCard,
  KanbanComment,
  InsertKanbanComment,
} from "./kanban/kanban-core";

export {
  taskSubtasks,
  insertTaskSubtaskSchema,
  taskChecklists,
  insertTaskChecklistSchema,
  taskChecklistItems,
  insertTaskChecklistItemSchema,
  taskTags,
  insertTaskTagSchema,
  taskCardTags,
  insertTaskCardTagSchema,
  taskReminders,
  insertTaskReminderSchema,
  taskTimeEntries,
  insertTaskTimeEntrySchema,
  taskCollaborators,
  insertTaskCollaboratorSchema,
  taskTemplates,
  insertTaskTemplateSchema,
  taskFiles,
  insertTaskFileSchema,
  taskStatusHistory,
  insertTaskStatusHistorySchema,
  taskResults,
  insertTaskResultSchema,
  taskResultFiles,
  insertTaskResultFileSchema,
  taskChatMessages,
  insertTaskChatMessageSchema,
  taskChatMessageFiles,
  insertTaskChatMessageFileSchema,
  taskTimeTracks,
  insertTaskTimeTrackSchema,
  taskObservers,
  insertTaskObserverSchema,
  taskCoExecutors,
  insertTaskCoExecutorSchema,
  taskProjects,
  insertTaskProjectSchema,
  taskProjectMembers,
  insertTaskProjectMemberSchema,
  automationRobots,
  insertAutomationRobotSchema,
  taskFlows,
  insertTaskFlowSchema,
  taskNotifications,
  insertTaskNotificationSchema,
  taskViewPreferences,
  insertTaskViewPreferenceSchema,
} from "./kanban/kanban-extended";

export type {
  TaskSubtask,
  InsertTaskSubtask,
  TaskChecklist,
  InsertTaskChecklist,
  TaskChecklistItem,
  InsertTaskChecklistItem,
  TaskTag,
  InsertTaskTag,
  TaskCardTag,
  InsertTaskCardTag,
  TaskReminder,
  InsertTaskReminder,
  TaskTimeEntry,
  InsertTaskTimeEntry,
  TaskCollaborator,
  InsertTaskCollaborator,
  TaskTemplate,
  InsertTaskTemplate,
  TaskFile,
  InsertTaskFile,
  TaskStatusHistory,
  InsertTaskStatusHistory,
  TaskResult,
  InsertTaskResult,
  TaskResultFile,
  InsertTaskResultFile,
  TaskChatMessage,
  InsertTaskChatMessage,
  TaskChatMessageFile,
  InsertTaskChatMessageFile,
  TaskTimeTrack,
  InsertTaskTimeTrack,
  TaskObserver,
  InsertTaskObserver,
  TaskCoExecutor,
  InsertTaskCoExecutor,
  TaskProject,
  InsertTaskProject,
  TaskProjectMember,
  InsertTaskProjectMember,
  AutomationRobot,
  InsertAutomationRobot,
  TaskFlow,
  InsertTaskFlow,
  TaskNotification,
  InsertTaskNotification,
  TaskViewPreference,
  InsertTaskViewPreference,
} from "./kanban/kanban-extended";
