module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '..',
  testRegex: 'test/.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': ['ts-jest', {
      tsconfig: '<rootDir>/tsconfig.json',
      diagnostics: false,
      isolatedModules: true,
    }],
  },
  collectCoverageFrom: ['src/**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  setupFiles: ['reflect-metadata'],
  moduleNameMapper: {
    '^shared/guards/(.*)$': '<rootDir>/src/modules/shared/guards/$1',
    '^shared/decorators/(.*)$': '<rootDir>/src/modules/shared/decorators/$1',
    '^shared/interceptors/(.*)$': '<rootDir>/src/modules/shared/interceptors/$1',
    '^shared/infrastructure/(.*)$': '<rootDir>/src/modules/shared/infrastructure/$1',
    '^shared/domain/(.*)$': '<rootDir>/src/modules/shared/domain/$1',
    '^shared/result$': '<rootDir>/src/modules/shared/domain/result',
    '^@shared/domain/(.*)$': '<rootDir>/src/modules/shared/domain/$1',
    '^@shared/guards/(.*)$': '<rootDir>/src/modules/shared/guards/$1',
    '^@shared/decorators/(.*)$': '<rootDir>/src/modules/shared/decorators/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@shared/db(.*)$': '<rootDir>/src/shared/db/$1',
    '^@europrint/schemas$': '<rootDir>/src/shared/db/europrint-compat.ts',
    '^@workspace/db$': '<rootDir>/../../lib/db/dist/cjs/index.js',
    '^@workspace/db/(.*)$': '<rootDir>/../../lib/db/dist/cjs/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@core/(.*)$': '<rootDir>/src/common/$1',
  },
};
