/** @module constants-security-infra @description Sidebar navigation constants for Security (tz13), Facilities/MRO (tz14), and IoT & Camera (tz15) modules. */

import {
  ShieldCheck, ScanLine, UserCog, UserCheck, Lock, Camera, AlertTriangle,
  HardHat, Flame, Star, Fingerprint, Wrench, BarChart3, Calendar, Settings,
  Zap, DollarSign, Briefcase, UtensilsCrossed, Shirt, Package, Recycle,
  Droplets, Building2, Cpu, Wifi, Radio, Thermometer, Factory, MapPin,
  BrainCircuit, FileCheck, Users, Trophy, Database, MonitorDot, Gauge,
  FileText,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsSecurityInfra: Record<string, MenuGroup> = {
  tz13: {
    title: "Xavfsizlik",
    icon: Lock,
    defaultUrl: "camera-safety",
    items: [
      { title: "KIRISH NAZORATI", url: "", icon: Fingerprint, separator: true },
      { title: "Xavfsizlik Holati", url: "camera-safety", icon: ShieldCheck },
      { title: "Yuz Tanish Kuzatuv", url: "camera/monitoring", icon: ScanLine },
      { title: "Yuz Ro'yxatdan O'tish", url: "face-registration", icon: UserCog },
      { title: "Davomat", url: "security/attendance", icon: UserCheck },
      { title: "Zona Ruxsatlari", url: "security/zone-access", icon: Lock },
      { title: "KAMERA", url: "", icon: Camera, separator: true },
      { title: "Jonli Monitoring", url: "camera-live-monitoring", icon: Camera },
      { title: "Kameralar", url: "cameras", icon: Camera },
      { title: "Hodisalar", url: "camera-alerts", icon: AlertTriangle },
      { title: "HODISALAR VA XAVF", url: "", icon: HardHat, separator: true },
      { title: "PPE Nazorati", url: "security/ppe", icon: HardHat },
      { title: "Xavfli Material", url: "security/hazmat", icon: AlertTriangle },
      { title: "Evakuatsiya Rejasi", url: "security/evacuation", icon: Flame },
      { title: "REYTING", url: "", icon: Star, separator: true },
      { title: "Tashrif Nazorati", url: "security/visitors", icon: UserCheck },
      { title: "Xavfsizlik Reytingi", url: "security/rating", icon: Star },
    ],
  },
  tz14: {
    title: "Xo'jalik",
    icon: Wrench,
    defaultUrl: "mro/dashboard",
    items: [
      { title: "TEXNIK XIZMAT", url: "", icon: Wrench, separator: true },
      { title: "MRO Dashboard", url: "mro/dashboard", icon: BarChart3 },
      { title: "Ta'mirlash Buyurtmalari", url: "integration/mro", icon: Wrench },
      { title: "Preventive Maintenance", url: "mro/preventive", icon: Calendar },
      { title: "MRO Ehtiyot Qismlar", url: "mro/spare-parts", icon: Settings },
      { title: "KOMMUNAL", url: "", icon: Zap, separator: true },
      { title: "Elektr/Gaz/Suv", url: "mro/utilities", icon: Zap },
      { title: "Xarajat Nazorati", url: "mro/expense-control", icon: DollarSign },
      { title: "XO'JALIK", url: "", icon: Briefcase, separator: true },
      { title: "Oshxona va Ovqat", url: "mro/kitchen", icon: UtensilsCrossed },
      { title: "Forma Boshqaruvi", url: "mro/uniforms", icon: Shirt },
      { title: "Ofis Inventari", url: "mro/office-inventory", icon: Package },
      { title: "MUHIT", url: "", icon: Recycle, separator: true },
      { title: "Tozalash Xizmati", url: "mro/cleaning", icon: Droplets },
      { title: "Chiqindi Nazorati", url: "europrint/waste-tracking", icon: Recycle },
      { title: "Sanitariya", url: "mro/sanitation", icon: ShieldCheck },
      { title: "Bino Inventari", url: "mro/building-inventory", icon: Building2 },
    ],
  },
  tz15: {
    title: "IoT va Kamera",
    icon: Cpu,
    defaultUrl: "camera-dashboard",
    items: [
      { title: "IOT SENSORLAR", url: "", icon: Wifi, separator: true },
      { title: "IoT Dashboard", url: "iot/dashboard", icon: Radio },
      { title: "Sensor Monitoring", url: "iot/sensor-monitoring", icon: Thermometer },
      { title: "Mashina Holati", url: "camera-machines", icon: Factory },
      { title: "KAMERALAR", url: "", icon: Camera, separator: true },
      { title: "Kamera Dashboard", url: "camera-dashboard", icon: BarChart3 },
      { title: "Kameralar", url: "cameras", icon: Camera },
      { title: "Issiqlik Xaritasi", url: "camera-heatmap", icon: MapPin },
      { title: "AI TAHLIL", url: "", icon: BrainCircuit, separator: true },
      { title: "AI Nazorat Hub", url: "camera-ai", icon: BrainCircuit },
      { title: "Kamera Sifat Nazorati", url: "camera-quality", icon: FileCheck },
      { title: "Xodim Monitoring", url: "camera-employees", icon: Users },
      { title: "Xodim Reytingi", url: "camera-employee-ratings", icon: Trophy },
      { title: "AI Sozlamalar", url: "camera-settings", icon: Settings },
      { title: "TEXNIK", url: "", icon: Gauge, separator: true },
      { title: "Predictive Maintenance", url: "iot/predictive-maintenance", icon: MonitorDot },
      { title: "OEE Live", url: "iot/oee-live", icon: Gauge },
      { title: "Digital Twin", url: "iot/digital-twin", icon: Database },
      { title: "Ogohlantirishlar", url: "iot/alerts", icon: AlertTriangle },
      { title: "Hisobotlar", url: "camera-reports", icon: FileText },
    ],
  },
};
