/** @module constants-production @description Sidebar navigation constants for Quality Control (tz04), Technology (tz05), AI Planning (tz06), and Manufacturing/MES (tz07) modules. */

import {
  BarChart3, FlaskConical, Activity, ClipboardList, FileCheck,
  ShieldCheck, CheckCircle, ClipboardCheck, Truck, ClipboardX,
  MessageSquare, FileText, Award, BadgeCheck, TrendingUp, BrainCircuit,
  Settings, Layers, Package, RotateCcw, Network, Factory, Calculator,
  Users, BookMarked, ScrollText, GitBranch, Brain, Calendar, Zap,
  AlertTriangle, Gauge, Target, LayoutDashboard, Tablet, FileSpreadsheet,
  Map, Wrench, Star, Trophy,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsProduction: Record<string, MenuGroup> = {
  tz04: {
    title: "Sifat Nazorati",
    icon: ShieldCheck,
    defaultUrl: "qc/dashboard",
    items: [
      { title: "LABORATORIYA", url: "", icon: FlaskConical, separator: true },
      { title: "QC Dashboard", url: "qc/dashboard", icon: BarChart3 },
      { title: "Qog'oz Parametrlari", url: "qc/lab", icon: FlaskConical },
      { title: "Material Testlari", url: "qc/tests", icon: Activity },
      { title: "Parametrlar", url: "qc/parameters", icon: ClipboardList },
      { title: "Normalar", url: "qc/standards", icon: FileCheck },
      { title: "NAZORAT", url: "", icon: ShieldCheck, separator: true },
      { title: "Inline QC", url: "qc/approval", icon: CheckCircle },
      { title: "Yakuniy Tekshiruv", url: "qc/final", icon: ClipboardCheck },
      { title: "Yetkazuvchi Sifati", url: "qc/vendor-quality", icon: Truck },
      { title: "BRAK VA REKLAMATSIYA", url: "", icon: AlertTriangle, separator: true },
      { title: "Brak Boshqaruvi", url: "qc/defect-management", icon: ClipboardX },
      { title: "Reklamatsiya", url: "qc/complaints", icon: MessageSquare },
      { title: "HUJJATLAR", url: "", icon: FileText, separator: true },
      { title: "Sifat Sertifikatlari", url: "qc/certificates", icon: Award },
      { title: "ISO Hujjatlari", url: "qc/iso", icon: BadgeCheck },
      { title: "TAHLIL", url: "", icon: BrainCircuit, separator: true },
      { title: "Sifat Trendi", url: "qc/trends", icon: TrendingUp },
      { title: "AI Tahlil", url: "qc/ai-analysis", icon: BrainCircuit },
      { title: "Hisobotlar", url: "qc/reports", icon: FileText },
      { title: "Sozlamalar", url: "qc/settings", icon: Settings },
    ],
  },
  tz05: {
    title: "Texnologiya",
    icon: Layers,
    defaultUrl: "tech/approval",
    items: [
      { title: "TEXNIK TASDIQ", url: "", icon: CheckCircle, separator: true },
      { title: "Texnik Tasdiqlash", url: "tech/approval", icon: CheckCircle },
      { title: "Texnik Kartalar", url: "tech/cards", icon: FileText },
      { title: "MATERIAL", url: "", icon: Package, separator: true },
      { title: "BOM Tarkib", url: "erp/pp/bom", icon: Package },
      { title: "Material Muqobili", url: "tech/material-alternatives", icon: RotateCcw },
      { title: "MARSHRUTLAR", url: "", icon: Network, separator: true },
      { title: "Marshrutlar", url: "erp/pp/routing", icon: Network },
      { title: "Stanoq Tanlash", url: "tech/machine-selection", icon: Factory },
      { title: "XARAJAT", url: "", icon: Calculator, separator: true },
      { title: "Vaqt va Tannarx", url: "tech/time-cost", icon: Calculator },
      { title: "Xarajat Optimizatsiya", url: "tech/cost-optimization", icon: TrendingUp },
      { title: "MIJOZ TALABLARI", url: "", icon: Users, separator: true },
      { title: "Mijoz Maxsus Talablar", url: "tech/client-requirements", icon: BookMarked },
      { title: "TARIX", url: "", icon: ScrollText, separator: true },
      { title: "O'zgarishlar Tarixi", url: "tech/change-history", icon: ScrollText },
      { title: "Parallel Buyurtmalar", url: "tech/parallel-orders", icon: GitBranch },
    ],
  },
  tz06: {
    title: "AI Rejalashtirish",
    icon: Brain,
    defaultUrl: "ai-production-planning",
    items: [
      { title: "ASOSIY REJALASHTIRISH", url: "", icon: Brain, separator: true },
      { title: "AI Rejalashtirish", url: "ai-production-planning", icon: Brain },
      { title: "AI Rezervatsiya", url: "pp/ai-reservation", icon: Calendar },
      { title: "PP Dashboard", url: "pp/dashboard", icon: BarChart3 },
      { title: "KUNLIK / HAFTALIK / OYLIK", url: "", icon: Calendar, separator: true },
      { title: "Rejalashtirish", url: "planning", icon: Calendar },
      { title: "Smena Boshqaruvi", url: "pp/shift-management", icon: Users },
      { title: "Parallel Jarayonlar", url: "pp/parallel-processes", icon: GitBranch },
      { title: "SUPER ADMIN OVERRIDE", url: "", icon: TrendingUp, separator: true },
      { title: "Quvvat Rejasi", url: "erp/pp/capacity", icon: TrendingUp },
      { title: "Rush Order", url: "pp/rush-orders", icon: Zap },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "Bottleneck Tahlili", url: "pp/bottleneck", icon: AlertTriangle },
      { title: "Demand Forecasting", url: "pp/demand-forecast", icon: TrendingUp },
      { title: "What-if Tahlil", url: "pp/what-if", icon: GitBranch },
      { title: "Yetkazish Kalkulyator", url: "pp/delivery-calculator", icon: Calculator },
      { title: "Energiya Optimizatsiya", url: "pp/energy-optimization", icon: Zap },
      { title: "KPI VA OG'ISH", url: "", icon: Target, separator: true },
      { title: "OEE Monitor", url: "pp/oee-monitor", icon: Gauge },
      { title: "KPI va Og'ish", url: "pp/kpi-deviation", icon: Target },
      { title: "Real-time Progress", url: "pp/realtime-progress", icon: Activity },
    ],
  },
  tz07: {
    title: "Ishlab Chiqarish",
    icon: Tablet,
    defaultUrl: "mes/dashboard-home",
    items: [
      { title: "DASHBOARD", url: "", icon: LayoutDashboard, separator: true },
      { title: "MES Dashboard", url: "mes/dashboard-home", icon: LayoutDashboard },
      { title: "IOT PLANSHET", url: "", icon: Tablet, separator: true },
      { title: "IoT Planshet", url: "iot/tablet", icon: Tablet },
      { title: "Kunlik Reja", url: "iot/daily-view", icon: Calendar },
      { title: "ISHLAB CHIQARISH", url: "", icon: Factory, separator: true },
      { title: "Ish Markazlari", url: "mes/work-centers", icon: Factory },
      { title: "Mahsulotlar", url: "mes/products", icon: Package },
      { title: "Buyurtmalar", url: "production/orders", icon: FileSpreadsheet },
      { title: "To'xtashlar", url: "mes/downtimes", icon: AlertTriangle },
      { title: "Xodim Tayinlashlari", url: "mes/workers", icon: Users },
      { title: "OEE Monitoring", url: "mes/oee-monitor", icon: Gauge },
      { title: "Sabablar Logi", url: "mes/reason-log", icon: ScrollText },
      { title: "SMENA", url: "", icon: Users, separator: true },
      { title: "Ishlab Chiqarish Monitor", url: "iot/dashboard", icon: BarChart3 },
      { title: "Zona Boshqaruvi", url: "mes/zone-management", icon: Map },
      { title: "SENSOR VA KAMERA", url: "", icon: Settings, separator: true },
      { title: "Texnik Xizmat So'rovi", url: "mes/maintenance-request", icon: Wrench },
      { title: "BAHOLASH", url: "", icon: Star, separator: true },
      { title: "Gamifikatsiya", url: "mes/gamification", icon: Trophy },
      { title: "Uskuna Normalari", url: "mes/machine-norms", icon: Settings },
      { title: "Smena Topshirish", url: "mes/smena-handover", icon: Calendar },
      { title: "KAIZEN", url: "", icon: Zap, separator: true },
      { title: "Kaizen Boshqaruvi", url: "kaizen", icon: Zap },
    ],
  },
};
