/** @module constants-finance @description Sidebar navigation constants for the Finance/Accounting (tz10) module, including GL, CFO dashboard, POS, tax management, and cost centres. */

import {
  BookOpen, Crown, BarChart3, BrainCircuit, LayoutDashboard, FileText,
  Calendar, TrendingUp, Target, FileCheck, Users, Truck, CheckCircle,
  Banknote, DollarSign, ShoppingCart, Package, MonitorDot, Calculator,
  ClipboardCheck, Building2, RotateCcw, FileSpreadsheet, ScrollText,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsFinance: Record<string, MenuGroup> = {
  tz10: {
    title: "Moliya",
    icon: TrendingUp,
    defaultUrl: "cfo-dashboard",
    items: [
      { title: "GL / IKKI YOQLAMA", url: "", icon: BookOpen, separator: true },
      { title: "CFO", url: "cfo", icon: Crown },
      { title: "CFO Dashboard", url: "cfo-dashboard", icon: BarChart3 },
      { title: "AI Moliya", url: "ai/finance", icon: BrainCircuit },
      { title: "Bosh Buxgalter", url: "finance-dashboard", icon: LayoutDashboard },
      { title: "GL Hujjatlar", url: "accounting/gl-documents", icon: FileText },
      { title: "Hisoblar Rejasi", url: "accounting/chart-of-accounts", icon: BookOpen },
      { title: "Davr Yopish", url: "accounting/period-closing", icon: Calendar },
      { title: "HISOBOTLAR", url: "", icon: FileText, separator: true },
      { title: "Pul Oqimi", url: "finance/cashflow", icon: TrendingUp },
      { title: "Byudjet", url: "finance/budgets", icon: Target },
      { title: "Foyda Tahlili", url: "finance/profitability", icon: BarChart3 },
      { title: "Hisobotlar", url: "finance/reports", icon: FileCheck },
      { title: "DEBITOR / KREDITOR", url: "", icon: Users, separator: true },
      { title: "Debitorlar", url: "accounting/ar", icon: Users },
      { title: "Kreditorlar", url: "accounting/ap", icon: Truck },
      { title: "Moliya Tasdiqlash", url: "finance/approval", icon: CheckCircle },
      { title: "AVANS VA KASSA", url: "", icon: Banknote, separator: true },
      { title: "Kassa", url: "accounting/cash-register", icon: DollarSign },
      { title: "Kirim/Chiqim", url: "accounting/income-expense", icon: TrendingUp },
      { title: "POS TIZIMI", url: "", icon: ShoppingCart, separator: true },
      { title: "POS Kassa", url: "pos/dashboard", icon: ShoppingCart },
      { title: "Inventar Boshqaruvi", url: "pos/inventory", icon: Package },
      { title: "POS Monitor", url: "pos-monitor", icon: MonitorDot },
      { title: "Ish Haqi", url: "accounting/payroll-automation", icon: Calculator },
      { title: "TANNARX", url: "", icon: Calculator, separator: true },
      { title: "Buyurtma Tannarxi", url: "finance/order-costing", icon: Calculator },
      { title: "Ombor Hisobi", url: "accounting/materials", icon: Package },
      { title: "Inventarizatsiya", url: "accounting/inventory-valuation", icon: ClipboardCheck },
      { title: "Asosiy Vositalar", url: "accounting/asset-management", icon: Building2 },
      { title: "Xarajat Markazlari", url: "fi/cost-centers", icon: Building2 },
      { title: "Transfer Pricing", url: "fi/transfer-pricing", icon: RotateCcw },
      { title: "SOLIQLAR", url: "", icon: FileSpreadsheet, separator: true },
      { title: "Ichki Soliqlar", url: "fi/tax-management", icon: FileSpreadsheet },
      { title: "Soliq Kalendari", url: "fi/tax-calendar", icon: Calendar },
      { title: "CFO BOSHQARUV", url: "", icon: Crown, separator: true },
      { title: "Audit Log", url: "fi/audit-log", icon: ScrollText },
      { title: "Moliyaviy Risk AI", url: "fi/risk-ai", icon: BrainCircuit },
    ],
  },
};
