/** @module constants-sales-crm @description Sidebar navigation constants for Sales/CRM (tz01), Marketing (tz02), and Design (tz03) modules. */

import {
  Users, BarChart3, Building2, ShoppingCart, BrainCircuit, FileText,
  FileCheck, Plus, FolderKanban, LayoutDashboard, Target, Package,
  CreditCard, Banknote, Settings, Calendar, Inbox, MessageSquare,
  TrendingUp, Globe, GitBranch, Scale, HeartPulse, DollarSign,
  Palette, Sparkles, Boxes, BookMarked, Library, Layers, Hammer,
  Calculator,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsSalesCrm: Record<string, MenuGroup> = {
  tz01: {
    title: "Savdo va CRM",
    icon: ShoppingCart,
    defaultUrl: "sd/dashboard",
    items: [
      { title: "MIJOZLAR", url: "", icon: Users, separator: true },
      { title: "SD Dashboard", url: "sd/dashboard", icon: BarChart3 },
      { title: "Mijozlar", url: "sd/customers", icon: Building2 },
      { title: "Lidlar", url: "crm-workspace", icon: Users },
      { title: "SOTISH", url: "", icon: ShoppingCart, separator: true },
      { title: "Sotish Paneli", url: "sales", icon: ShoppingCart },
      { title: "AI CRM", url: "ai/crm", icon: BrainCircuit },
      { title: "Taklifnomalar", url: "sd/sales-quotes", icon: FileText },
      { title: "Buyurtmalar", url: "sd/sales-orders", icon: ShoppingCart },
      { title: "Papka Buyurtmalari", url: "papka-orders", icon: FileText },
      { title: "Shartnomalar", url: "sd/contracts", icon: FileCheck },
      { title: "Buyurtma Yaratish", url: "order-create", icon: Plus },
      { title: "Buyurtma Workflow", url: "order-workflow", icon: FolderKanban },
      { title: "MENEJER PANELI", url: "", icon: LayoutDashboard, separator: true },
      { title: "Menejer Paneli", url: "sd/manager-panel", icon: LayoutDashboard },
      { title: "Kvota Dashboard", url: "sd/quota-dashboard", icon: Target },
      { title: "Ombor Ijara", url: "sd/warehouse-rental", icon: Package },
      { title: "TO'LOV", url: "", icon: CreditCard, separator: true },
      { title: "To'lovlar", url: "sd/sales-payments", icon: CreditCard },
      { title: "70% Avans Nazorat", url: "sd/advance-control", icon: Banknote },
      { title: "MIJOZ 360", url: "", icon: Users, separator: true },
      { title: "Customer 360", url: "sd/customers", icon: Users },
      { title: "SOZLAMALAR", url: "", icon: Settings, separator: true },
      { title: "KPI", url: "sd/kpi", icon: Target },
      { title: "Sozlamalar", url: "sd/settings", icon: Settings },
    ],
  },
  tz02: {
    title: "Marketing",
    icon: Target,
    defaultUrl: "marketing/dashboard",
    items: [
      { title: "LEAD VA KAMPANIYA", url: "", icon: Users, separator: true },
      { title: "Dashboard", url: "marketing/dashboard", icon: BarChart3 },
      { title: "Lidlar", url: "marketing/leads", icon: Users },
      { title: "Kampaniyalar", url: "marketing/campaigns", icon: Target },
      { title: "KONTENT", url: "", icon: FileText, separator: true },
      { title: "Kontent", url: "marketing/content", icon: FileText },
      { title: "Social Inbox", url: "marketing/social-inbox", icon: Inbox },
      { title: "Taqvim", url: "marketing/calendar", icon: Calendar },
      { title: "PR VA TADBIRLAR", url: "", icon: MessageSquare, separator: true },
      { title: "Ko'rgazmalar", url: "marketing/exhibitions", icon: Building2 },
      { title: "PR Faoliyat", url: "marketing/pr", icon: MessageSquare },
      { title: "ANALITIKA", url: "", icon: BarChart3, separator: true },
      { title: "Tahlil (ROI/ROAS)", url: "marketing/analytics", icon: TrendingUp },
      { title: "SEO Monitoring", url: "marketing/seo", icon: Globe },
      { title: "A/B Testing", url: "marketing/ab-testing", icon: GitBranch },
      { title: "Raqobatchilar", url: "marketing/competitors", icon: Scale },
      { title: "NPS va Churn", url: "marketing/nps-churn", icon: HeartPulse },
      { title: "VOSITALAR", url: "", icon: Settings, separator: true },
      { title: "Web sayt CMS", url: "marketing/website-cms", icon: Globe },
      { title: "Byudjet", url: "marketing/budget", icon: DollarSign },
      { title: "Sozlamalar", url: "marketing/settings", icon: Settings },
    ],
  },
  tz03: {
    title: "Dizayn",
    icon: Palette,
    defaultUrl: "design/dashboard",
    items: [
      { title: "DIZAYN", url: "", icon: Palette, separator: true },
      { title: "Dizayn Dashboard", url: "design/dashboard", icon: Palette },
      { title: "Dizayn Buyurtmalar", url: "design/orders", icon: Package },
      { title: "Dizayn Tasdiqlash", url: "design/approval", icon: FileCheck },
      { title: "AI VA VOSITALAR", url: "", icon: Sparkles, separator: true },
      { title: "AI Generator", url: "design/generator", icon: Sparkles },
      { title: "AI Dizayn Tekshiruvi", url: "design/ai-review", icon: BrainCircuit },
      { title: "3D Mockup", url: "design/3d-mockup", icon: Boxes },
      { title: "Dizayn Taqqoslash", url: "design/comparison", icon: Scale },
      { title: "KUTUBXONA", url: "", icon: Library, separator: true },
      { title: "Dizayn Kutubxona", url: "design/library", icon: Library },
      { title: "Brend Guidelines", url: "design/brand-guidelines", icon: BookMarked },
      { title: "QOLIPLAR VA ASBOBLAR", url: "", icon: Layers, separator: true },
      { title: "Qoliplar Boshqaruvi", url: "design/templates", icon: Layers },
      { title: "Asboblar va Plastinalar", url: "design/tools", icon: Hammer },
      { title: "MOLIYA", url: "", icon: DollarSign, separator: true },
      { title: "Dizayn Tannarxi", url: "design/costing", icon: Calculator },
    ],
  },
};
