/**
 * @module constants-groups-a
 * @description Sidebar menu groups tz01–tz08 (Rule 16 split from constants.ts).
 */
import {
  LayoutDashboard, Users, BarChart3, Building2, ShoppingCart, FileText, FileCheck,
  Plus, FolderKanban, Target, Package, CreditCard, Banknote, Settings, Inbox,
  Calendar, MessageSquare, TrendingUp, Globe, GitBranch, Scale, HeartPulse,
  DollarSign, Palette, CheckCircle, Sparkles, BrainCircuit, Boxes, Library,
  BookMarked, Layers, Hammer, Calculator, FlaskConical, Activity, ClipboardList,
  ShieldCheck, ClipboardCheck, Truck, ClipboardX, Award, BadgeCheck, RotateCcw,
  Network, Factory, ScrollText, Brain, Crown, Zap, AlertTriangle, Gauge, Tablet,
  FileSpreadsheet, Map, Wrench, Star, Trophy, PackageCheck, Lock, Barcode,
  Recycle, Wifi,
} from "lucide-react";

export const menuGroupsA = {
  tz01: {
    title: "Savdo va CRM",
    icon: ShoppingCart,
    defaultUrl: "sd/dashboard",
    items: [
      { title: "MIJOZLAR", url: "", icon: Users, separator: true },
      { title: "SD Dashboard", url: "sd/dashboard", icon: BarChart3 },
      { title: "Mijozlar", url: "sd/customers", icon: Building2 },
      { title: "Lidlar", url: "crm-workspace", icon: Users },
      { title: "Leedlar",         url: "sd/leads",      icon: Target },
      { title: "Yetkazib berish", url: "sd/deliveries", icon: Truck  },
      { title: "SOTISH", url: "", icon: ShoppingCart, separator: true },
      { title: "Sotish Paneli", url: "sales", icon: ShoppingCart },
      { title: "AI CRM", url: "ai/crm", icon: BrainCircuit },
      { title: "Taklifnomalar", url: "sd/sales-quotes", icon: FileText },
      { title: "Buyurtmalar", url: "sd/sales-orders", icon: ShoppingCart },
      { title: "Papka Buyurtmalari", url: "papka-orders", icon: FileText },
      { title: "Shartnomalar", url: "sd/contracts", icon: FileCheck },
      { title: "Buyurtma Yaratish", url: "order-create", icon: Plus },
      { title: "Buyurtma Workflow", url: "order-workflow", icon: FolderKanban },
      { title: "MENEJER PANELI", url: "", icon: LayoutDashboard, separator: true },
      { title: "Menejer Paneli", url: "sd/manager-panel", icon: LayoutDashboard },
      { title: "Kvota Dashboard", url: "sd/quota-dashboard", icon: Target },
      { title: "Ombor Ijara", url: "sd/warehouse-rental", icon: Package },
      { title: "TO'LOV", url: "", icon: CreditCard, separator: true },
      { title: "To'lovlar", url: "sd/sales-payments", icon: CreditCard },
      { title: "70% Avans Nazorat", url: "sd/advance-control", icon: Banknote },
      { title: "SOZLAMALAR", url: "", icon: Settings, separator: true },
      { title: "KPI", url: "sd/kpi", icon: Target },
      { title: "Sozlamalar", url: "sd/settings", icon: Settings },
    ],
  },
  tz02: {
    title: "Marketing",
    icon: Target,
    defaultUrl: "marketing/dashboard",
    items: [
      { title: "LEAD VA KAMPANIYA", url: "", icon: Users, separator: true },
      { title: "Dashboard", url: "marketing/dashboard", icon: BarChart3 },
      { title: "Lidlar", url: "marketing/leads", icon: Users },
      { title: "Kampaniyalar", url: "marketing/campaigns", icon: Target },
      { title: "KONTENT", url: "", icon: FileText, separator: true },
      { title: "Kontent", url: "marketing/content", icon: FileText },
      { title: "Social Inbox", url: "marketing/social-inbox", icon: Inbox },
      { title: "Taqvim", url: "marketing/calendar", icon: Calendar },
      { title: "PR VA TADBIRLAR", url: "", icon: MessageSquare, separator: true },
      { title: "Ko'rgazmalar", url: "marketing/exhibitions", icon: Building2 },
      { title: "PR Faoliyat", url: "marketing/pr", icon: MessageSquare },
      { title: "ANALITIKA", url: "", icon: BarChart3, separator: true },
      { title: "Tahlil (ROI/ROAS)", url: "marketing/analytics", icon: TrendingUp },
      { title: "SEO Monitoring", url: "marketing/seo", icon: Globe },
      { title: "A/B Testing", url: "marketing/ab-testing", icon: GitBranch },
      { title: "Raqobatchilar", url: "marketing/competitors", icon: Scale },
      { title: "NPS va Churn", url: "marketing/nps-churn", icon: HeartPulse },
      { title: "VOSITALAR", url: "", icon: Settings, separator: true },
      { title: "Web sayt CMS", url: "marketing/website-cms", icon: Globe },
      { title: "Byudjet", url: "marketing/budget", icon: DollarSign },
      { title: "Sozlamalar", url: "marketing/settings", icon: Settings },
    ],
  },
  tz03: {
    title: "Dizayn",
    icon: Palette,
    defaultUrl: "design/dashboard",
    items: [
      { title: "DIZAYN", url: "", icon: Palette, separator: true },
      { title: "Dizayn Dashboard", url: "design/dashboard", icon: Palette },
      { title: "Dizayn Buyurtmalar", url: "design/orders", icon: Package },
      { title: "Dizayn Tasdiqlash", url: "design/approval", icon: CheckCircle },
      { title: "AI VA VOSITALAR", url: "", icon: Sparkles, separator: true },
      { title: "AI Generator", url: "design/generator", icon: Sparkles },
      { title: "AI Dizayn Tekshiruvi", url: "design/ai-review", icon: BrainCircuit },
      { title: "3D Mockup", url: "design/3d-mockup", icon: Boxes },
      { title: "Dizayn Taqqoslash", url: "design/comparison", icon: Scale },
      { title: "KUTUBXONA", url: "", icon: Library, separator: true },
      { title: "Dizayn Kutubxona", url: "design/library", icon: Library },
      { title: "Brend Guidelines", url: "design/brand-guidelines", icon: BookMarked },
      { title: "QOLIPLAR VA ASBOBLAR", url: "", icon: Layers, separator: true },
      { title: "Qoliplar Boshqaruvi", url: "design/templates", icon: Layers },
      { title: "Asboblar va Plastinalar", url: "design/tools", icon: Hammer },
      { title: "MOLIYA", url: "", icon: DollarSign, separator: true },
      { title: "Dizayn Tannarxi", url: "design/costing", icon: Calculator },
    ],
  },
  tz04: {
    title: "Sifat Nazorati",
    icon: ShieldCheck,
    defaultUrl: "qc/dashboard",
    items: [
      { title: "LABORATORIYA", url: "", icon: FlaskConical, separator: true },
      { title: "QC Dashboard", url: "qc/dashboard", icon: BarChart3 },
      { title: "Qog'oz Parametrlari", url: "qc/lab", icon: FlaskConical },
      { title: "Material Testlari", url: "qc/tests", icon: Activity },
      { title: "Parametrlar", url: "qc/parameters", icon: ClipboardList },
      { title: "Normalar", url: "qc/standards", icon: FileCheck },
      { title: "NAZORAT", url: "", icon: ShieldCheck, separator: true },
      { title: "Inline QC", url: "qc/approval", icon: CheckCircle },
      { title: "Yakuniy Tekshiruv", url: "qc/final", icon: ClipboardCheck },
      { title: "Yetkazuvchi Sifati", url: "qc/vendor-quality", icon: Truck },
      { title: "BRAK VA REKLAMATSIYA", url: "", icon: AlertTriangle, separator: true },
      { title: "Brak Boshqaruvi", url: "qc/defect-management", icon: ClipboardX },
      { title: "Reklamatsiya", url: "qc/complaints", icon: MessageSquare },
      { title: "HUJJATLAR", url: "", icon: FileText, separator: true },
      { title: "Sifat Sertifikatlari", url: "qc/certificates", icon: Award },
      { title: "ISO Hujjatlari", url: "qc/iso", icon: BadgeCheck },
      { title: "TAHLIL", url: "", icon: BrainCircuit, separator: true },
      { title: "Sifat Trendi", url: "qc/trends", icon: TrendingUp },
      { title: "AI Tahlil", url: "qc/ai-analysis", icon: BrainCircuit },
      { title: "Hisobotlar", url: "qc/reports", icon: FileText },
      { title: "Sozlamalar", url: "qc/settings", icon: Settings },
    ],
  },
  tz05: {
    title: "Texnologiya",
    icon: Layers,
    defaultUrl: "tech/approval",
    items: [
      { title: "TEXNIK TASDIQ", url: "", icon: CheckCircle, separator: true },
      { title: "Texnik Tasdiqlash", url: "tech/approval", icon: CheckCircle },
      { title: "Texnik Kartalar", url: "tech/cards", icon: FileText },
      { title: "MATERIAL", url: "", icon: Package, separator: true },
      { title: "BOM Tarkib", url: "erp/pp/bom", icon: Package },
      { title: "Material Muqobili", url: "tech/material-alternatives", icon: RotateCcw },
      { title: "MARSHRUTLAR", url: "", icon: Network, separator: true },
      { title: "Marshrutlar", url: "erp/pp/routing", icon: Network },
      { title: "Stanoq Tanlash", url: "tech/machine-selection", icon: Factory },
      { title: "XARAJAT", url: "", icon: Calculator, separator: true },
      { title: "Vaqt va Tannarx", url: "tech/time-cost", icon: Calculator },
      { title: "Xarajat Optimizatsiya", url: "tech/cost-optimization", icon: TrendingUp },
      { title: "MIJOZ TALABLARI", url: "", icon: Users, separator: true },
      { title: "Mijoz Maxsus Talablar", url: "tech/client-requirements", icon: BookMarked },
      { title: "TARIX", url: "", icon: ScrollText, separator: true },
      { title: "O'zgarishlar Tarixi", url: "tech/change-history", icon: ScrollText },
      { title: "Parallel Buyurtmalar", url: "tech/parallel-orders", icon: GitBranch },
    ],
  },
  tz06: {
    title: "AI Rejalashtirish",
    icon: Brain,
    defaultUrl: "ai-production-planning",
    items: [
      { title: "ASOSIY REJALASHTIRISH", url: "", icon: Brain, separator: true },
      { title: "AI Rejalashtirish", url: "ai-production-planning", icon: Brain },
      { title: "AI Rezervatsiya", url: "pp/ai-reservation", icon: Calendar },
      { title: "PP Dashboard", url: "pp/dashboard", icon: BarChart3 },
      { title: "KUNLIK / HAFTALIK / OYLIK", url: "", icon: Calendar, separator: true },
      { title: "Rejalashtirish", url: "planning", icon: Calendar },
      { title: "Smena Boshqaruvi", url: "pp/shift-management", icon: Users },
      { title: "Parallel Jarayonlar", url: "pp/parallel-processes", icon: GitBranch },
      { title: "SUPER ADMIN OVERRIDE", url: "", icon: Crown, separator: true },
      { title: "Quvvat Rejasi", url: "erp/pp/capacity", icon: TrendingUp },
      { title: "Rush Order", url: "pp/rush-orders", icon: Zap },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "Bottleneck Tahlili", url: "pp/bottleneck", icon: AlertTriangle },
      { title: "Demand Forecasting", url: "pp/demand-forecast", icon: TrendingUp },
      { title: "What-if Tahlil", url: "pp/what-if", icon: GitBranch },
      { title: "Yetkazish Kalkulyator", url: "pp/delivery-calculator", icon: Calculator },
      { title: "Energiya Optimizatsiya", url: "pp/energy-optimization", icon: Zap },
      { title: "KPI VA OG'ISH", url: "", icon: Target, separator: true },
      { title: "OEE Monitor", url: "pp/oee-monitor", icon: Gauge },
      { title: "KPI va Og'ish", url: "pp/kpi-deviation", icon: Target },
      { title: "Real-time Progress", url: "pp/realtime-progress", icon: Activity },
    ],
  },
  tz07: {
    title: "Ishlab Chiqarish",
    icon: Tablet,
    defaultUrl: "mes/dashboard-home",
    items: [
      { title: "DASHBOARD", url: "", icon: LayoutDashboard, separator: true },
      { title: "MES Dashboard", url: "mes/dashboard-home", icon: LayoutDashboard },
      { title: "IOT PLANSHET", url: "", icon: Tablet, separator: true },
      { title: "IoT Planshet", url: "iot/tablet", icon: Tablet },
      { title: "Kunlik Reja", url: "iot/daily-view", icon: Calendar },
      { title: "ISHLAB CHIQARISH", url: "", icon: Factory, separator: true },
      { title: "Ish Markazlari", url: "mes/work-centers", icon: Factory },
      { title: "Mahsulotlar", url: "mes/products", icon: Package },
      { title: "Buyurtmalar", url: "production/orders", icon: FileSpreadsheet },
      { title: "To'xtashlar", url: "mes/downtimes", icon: AlertTriangle },
      { title: "Xodim Tayinlashlari", url: "mes/workers", icon: Users },
      { title: "OEE Monitoring", url: "mes/oee-monitor", icon: Gauge },
      { title: "Sabablar Logi", url: "mes/reason-log", icon: ScrollText },
      { title: "SMENA", url: "", icon: Users, separator: true },
      // "Ishlab Chiqarish Monitor" iot/dashboard ga ishora qilardi — IoT modulida bor (tz15)
      { title: "Zona Boshqaruvi", url: "mes/zone-management", icon: Map },
      { title: "SENSOR VA KAMERA", url: "", icon: Wifi, separator: true },
      { title: "Texnik Xizmat So'rovi", url: "mes/maintenance-request", icon: Wrench },
      { title: "BAHOLASH", url: "", icon: Star, separator: true },
      { title: "Gamifikatsiya", url: "mes/gamification", icon: Trophy },
      { title: "Uskuna Normalari", url: "mes/machine-norms", icon: Settings },
      { title: "Smena Topshirish", url: "mes/smena-handover", icon: Calendar },
      { title: "KAIZEN", url: "", icon: Zap, separator: true },
      { title: "Kaizen Boshqaruvi", url: "kaizen", icon: Zap },
    ],
  },
  tz08: {
    title: "Ombor",
    icon: Package,
    defaultUrl: "warehouse/hub",
    items: [
      // 9 ombor-turi (RM-MAIN..MRO-STORE) endi Ombor Dashboard ICHIDA filter
      // (warehouse/hub/:code route saqlangan). Alohida sidebar yozuv EMAS — 2026-05-21 kanon.
      { title: "OMBORLAR", url: "", icon: Package, separator: true },
      { title: "Ombor Dashboard", url: "warehouse/hub", icon: BarChart3 },
      { title: "QABUL", url: "", icon: PackageCheck, separator: true },
      { title: "Qabul Akti (GRN)", url: "wms/grn", icon: PackageCheck },
      { title: "Reservation Panel", url: "wms/reservation", icon: Lock },
      { title: "INVENTAR", url: "", icon: ClipboardList, separator: true },
      { title: "Inventarizatsiya", url: "wms/inventory", icon: ClipboardCheck },
      { title: "Lot Traceability", url: "wms/lot-traceability", icon: Barcode },
      { title: "Barkod Tizimi", url: "warehouse/barcode-ops", icon: Barcode },
      { title: "Material 360°", url: "inventory/materials", icon: Package },
      { title: "HARAKAT", url: "", icon: FileText, separator: true },
      { title: "Ko'chirish Hujjatlari", url: "wms/transfer", icon: FileText },
      { title: "ICHKI SO'ROV", url: "", icon: MessageSquare, separator: true },
      { title: "Ichki So'rov", url: "wms/internal-requests", icon: MessageSquare },
      { title: "IJARA VA CHIQINDI", url: "", icon: DollarSign, separator: true },
      { title: "Tayyor Mahsulot Ijara", url: "wms/rental", icon: DollarSign },
      { title: "Chiqindilar", url: "warehouse/hub/SCRAP", icon: Recycle },
      { title: "INTEGRATSIYA", url: "", icon: GitBranch, separator: true },
      { title: "PP/MM/FI Integratsiya", url: "warehouse/integrations", icon: GitBranch },
    ],
  },
};
