import { LayoutDashboard, X,
  BookOpen,
  Users,
  ClipboardList,
  BarChart3,
  Settings,
  FileText,
  BrainCircuit,
  Brain,
  Award,
  Building2,
  Briefcase,
  MessageSquare,
  FileCheck,
  Trophy,
  Target,
  Calendar,
  UserCheck,
  Network,
  GraduationCap,
  MapPin,
  Factory,
  Package,
  DollarSign,
  Camera,
  TrendingUp,
  ShieldCheck,
  Palette,
  Sparkles,
  Library,
  Truck,
  ShoppingCart,
  CreditCard,
  Tablet,
  Calculator,
  Cpu,
  ChevronRight,
  ChevronLeft,
  CheckCircle,
  Activity,
  ScanLine,
  UserCog,
  Plus,
  FileQuestion,
  ClipboardCheck,
  Lock,
  Barcode,
  Rocket,
  Crown,
  Grid3X3,
  Mic,
  ScrollText,
  Boxes,
  Wrench,
  Beaker,
  Trash2,
  Inbox,
  Globe,
  Layers,
  Radio,
  Zap,
  AlertTriangle,
  Hammer,
  Gauge,
  Navigation,
  Droplets,
  Car,
  Scale,
  Bug,
  HeartPulse,
  BookMarked,
  BadgeCheck,
  Star,
  HardHat,
  Database,
  Key,
  PlayCircle,
  UserMinus,
  UserPlus,
  Fingerprint,
  FileSpreadsheet,
  Banknote,
  GitBranch,
  Wifi,
  MonitorDot,
  Flame,
  PackageCheck,
  RotateCcw,
  Thermometer,
  FlaskConical,
  UtensilsCrossed,
  Shirt,
  Recycle,
  ClipboardX,
  Map,
  Fuel,
  Server,
  PanelLeftClose,
  FolderKanban,
  Cake,
  Megaphone
  } from "lucide-react";
  import { MenuGroup } from "./types";
  import { translateHrModule } from "./hrNavI18n";
  import { FEATURE_MARKETING } from "@/lib/feature-flags";

  export const menuGroups = {
  tz01: {
    title: "Savdo va CRM",
    icon: ShoppingCart,
    defaultUrl: "sd/dashboard",
    items: [
      { title: "MIJOZLAR", url: "", icon: Users, separator: true },
      { title: "SD Dashboard", url: "sd/dashboard", icon: BarChart3 },
      { title: "Mijozlar", url: "sd/customers", icon: Building2 },
      { title: "Lidlar", url: "crm-workspace", icon: Users },
      { title: "SOTISH", url: "", icon: ShoppingCart, separator: true },
      { title: "Sotish Paneli", url: "sales", icon: ShoppingCart },
      { title: "AI CRM", url: "ai/crm", icon: BrainCircuit },
      { title: "Taklifnomalar", url: "sd/sales-quotes", icon: FileText },
      { title: "Buyurtmalar", url: "sd/sales-orders", icon: ShoppingCart },
      { title: "Papka Buyurtmalari", url: "papka-orders", icon: FileText },
      { title: "Shartnomalar", url: "sd/contracts", icon: FileCheck },
      { title: "Buyurtma Yaratish", url: "order-create", icon: Plus },
      { title: "Buyurtma Workflow", url: "order-workflow", icon: FolderKanban },
      // Konsolidatsiya: "Menejer Paneli" + "Kvota Dashboard" asosiy SD Dashboardga
      // yig'ildi (dashboard quick-link'lari orqali ochiladi) — 4 ta emas, 1 ta dashboard.
      { title: "QO'SHIMCHA", url: "", icon: Package, separator: true },
      { title: "Ombor Ijara", url: "sd/warehouse-rental", icon: Package },
      { title: "TO'LOV", url: "", icon: CreditCard, separator: true },
      { title: "To'lovlar", url: "sd/sales-payments", icon: CreditCard },
      { title: "70% Avans Nazorat", url: "sd/advance-control", icon: Banknote },
      { title: "SOZLAMALAR", url: "", icon: Settings, separator: true },
      { title: "KPI", url: "sd/kpi", icon: Target },
      { title: "Sozlamalar", url: "sd/settings", icon: Settings },
    ]
  },
  tz02: {
    title: "Marketing",
    icon: Target,
    defaultUrl: "marketing/dashboard",
    items: [
      { title: "LEAD VA KAMPANIYA", url: "", icon: Users, separator: true },
      { title: "Dashboard", url: "marketing/dashboard", icon: BarChart3 },
      { title: "Lidlar", url: "marketing/leads", icon: Users },
      { title: "Kampaniyalar", url: "marketing/campaigns", icon: Target },
      { title: "KONTENT", url: "", icon: FileText, separator: true },
      { title: "Kontent", url: "marketing/content", icon: FileText },
      { title: "Social Inbox", url: "marketing/social-inbox", icon: Inbox },
      { title: "Taqvim", url: "marketing/calendar", icon: Calendar },
      { title: "PR VA TADBIRLAR", url: "", icon: MessageSquare, separator: true },
      { title: "Ko'rgazmalar", url: "marketing/exhibitions", icon: Building2 },
      { title: "PR Faoliyat", url: "marketing/pr", icon: MessageSquare },
      { title: "ANALITIKA", url: "", icon: BarChart3, separator: true },
      { title: "Tahlil (ROI/ROAS)", url: "marketing/analytics", icon: TrendingUp },
      { title: "SEO Monitoring", url: "marketing/seo", icon: Globe },
      { title: "A/B Testing", url: "marketing/ab-testing", icon: GitBranch },
      { title: "Raqobatchilar", url: "marketing/competitors", icon: Scale },
      { title: "NPS va Churn", url: "marketing/nps-churn", icon: HeartPulse },
      { title: "VOSITALAR", url: "", icon: Settings, separator: true },
      { title: "Web sayt CMS", url: "marketing/website-cms", icon: Globe },
      { title: "Byudjet", url: "marketing/budget", icon: DollarSign },
      { title: "Sozlamalar", url: "marketing/settings", icon: Settings },
    ]
  },
  tz03: {
    title: "Dizayn",
    icon: Palette,
    defaultUrl: "design/dashboard",
    items: [
      { title: "DIZAYN", url: "", icon: Palette, separator: true },
      { title: "Dizayn Dashboard", url: "design/dashboard", icon: Palette },
      { title: "Dizayn Buyurtmalar", url: "design/orders", icon: Package },
      { title: "Dizayn Tasdiqlash", url: "design/approval", icon: CheckCircle },
      { title: "AI VA VOSITALAR", url: "", icon: Sparkles, separator: true },
      { title: "AI Generator", url: "design/generator", icon: Sparkles },
      { title: "AI Dizayn Tekshiruvi", url: "design/ai-review", icon: BrainCircuit },
      { title: "3D Mockup", url: "design/3d-mockup", icon: Boxes },
      { title: "Dizayn Taqqoslash", url: "design/comparison", icon: Scale },
      { title: "KUTUBXONA", url: "", icon: Library, separator: true },
      { title: "Dizayn Kutubxona", url: "design/library", icon: Library },
      { title: "Brend Guidelines", url: "design/brand-guidelines", icon: BookMarked },
      { title: "QOLIPLAR VA ASBOBLAR", url: "", icon: Layers, separator: true },
      { title: "Qoliplar Boshqaruvi", url: "design/templates", icon: Layers },
      { title: "Asboblar va Plastinalar", url: "design/tools", icon: Hammer },
      { title: "MOLIYA", url: "", icon: DollarSign, separator: true },
      { title: "Dizayn Tannarxi", url: "design/costing", icon: Calculator },
    ]
  },
  tz04: {
    title: "Sifat Nazorati",
    icon: ShieldCheck,
    defaultUrl: "qc/dashboard",
    items: [
      { title: "LABORATORIYA", url: "", icon: FlaskConical, separator: true },
      { title: "QC Dashboard", url: "qc/dashboard", icon: BarChart3 },
      { title: "Qog'oz Parametrlari", url: "qc/lab", icon: FlaskConical },
      { title: "Material Testlari", url: "qc/tests", icon: Activity },
      { title: "Parametrlar", url: "qc/parameters", icon: ClipboardList },
      { title: "Normalar", url: "qc/standards", icon: FileCheck },
      { title: "NAZORAT", url: "", icon: ShieldCheck, separator: true },
      { title: "Inline QC", url: "qc/approval", icon: CheckCircle },
      { title: "Yakuniy Tekshiruv", url: "qc/final", icon: ClipboardCheck },
      { title: "Yetkazuvchi Sifati", url: "qc/vendor-quality", icon: Truck },
      { title: "BRAK VA REKLAMATSIYA", url: "", icon: AlertTriangle, separator: true },
      { title: "Brak Boshqaruvi", url: "qc/defect-management", icon: ClipboardX },
      { title: "Reklamatsiya", url: "qc/complaints", icon: MessageSquare },
      { title: "HUJJATLAR", url: "", icon: FileText, separator: true },
      { title: "Sifat Sertifikatlari", url: "qc/certificates", icon: Award },
      { title: "ISO Hujjatlari", url: "qc/iso", icon: BadgeCheck },
      { title: "TAHLIL", url: "", icon: BrainCircuit, separator: true },
      { title: "Sifat Trendi", url: "qc/trends", icon: TrendingUp },
      { title: "AI Tahlil", url: "qc/ai-analysis", icon: BrainCircuit },
      { title: "Hisobotlar", url: "qc/reports", icon: FileText },
      { title: "Sozlamalar", url: "qc/settings", icon: Settings },
    ]
  },
  tz05: {
    title: "Texnologiya",
    icon: Layers,
    defaultUrl: "tech/approval",
    items: [
      { title: "TEXNIK TASDIQ", url: "", icon: CheckCircle, separator: true },
      { title: "Texnik Tasdiqlash", url: "tech/approval", icon: CheckCircle },
      { title: "Texnik Kartalar", url: "tech/cards", icon: FileText },
      { title: "MATERIAL", url: "", icon: Package, separator: true },
      { title: "BOM Tarkib", url: "erp/pp/bom", icon: Package },
      { title: "Material Muqobili", url: "tech/material-alternatives", icon: RotateCcw },
      { title: "MARSHRUTLAR", url: "", icon: Network, separator: true },
      { title: "Marshrutlar", url: "erp/pp/routing", icon: Network },
      { title: "Stanoq Tanlash", url: "tech/machine-selection", icon: Factory },
      { title: "XARAJAT", url: "", icon: Calculator, separator: true },
      { title: "Vaqt va Tannarx", url: "tech/time-cost", icon: Calculator },
      { title: "Xarajat Optimizatsiya", url: "tech/cost-optimization", icon: TrendingUp },
      { title: "MIJOZ TALABLARI", url: "", icon: Users, separator: true },
      { title: "Mijoz Maxsus Talablar", url: "tech/client-requirements", icon: BookMarked },
      { title: "TARIX", url: "", icon: ScrollText, separator: true },
      { title: "O'zgarishlar Tarixi", url: "tech/change-history", icon: ScrollText },
      { title: "Parallel Buyurtmalar", url: "tech/parallel-orders", icon: GitBranch },
    ]
  },
  tz06: {
    title: "AI Rejalashtirish",
    icon: Brain,
    defaultUrl: "ai-production-planning",
    items: [
      { title: "ASOSIY REJALASHTIRISH", url: "", icon: Brain, separator: true },
      { title: "AI Rejalashtirish", url: "ai-production-planning", icon: Brain },
      { title: "AI Rezervatsiya", url: "pp/ai-reservation", icon: Calendar },
      { title: "PP Dashboard", url: "pp/dashboard", icon: BarChart3 },
      { title: "KUNLIK / HAFTALIK / OYLIK", url: "", icon: Calendar, separator: true },
      { title: "Rejalashtirish", url: "planning", icon: Calendar },
      { title: "Smena Boshqaruvi", url: "pp/shift-management", icon: Users },
      { title: "Parallel Jarayonlar", url: "pp/parallel-processes", icon: GitBranch },
      { title: "SUPER ADMIN OVERRIDE", url: "", icon: Crown, separator: true },
      { title: "Quvvat Rejasi", url: "erp/pp/capacity", icon: TrendingUp },
      { title: "Rush Order", url: "pp/rush-orders", icon: Zap },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "Bottleneck Tahlili", url: "pp/bottleneck", icon: AlertTriangle },
      { title: "Demand Forecasting", url: "pp/demand-forecast", icon: TrendingUp },
      { title: "What-if Tahlil", url: "pp/what-if", icon: GitBranch },
      { title: "Yetkazish Kalkulyator", url: "pp/delivery-calculator", icon: Calculator },
      { title: "Energiya Optimizatsiya", url: "pp/energy-optimization", icon: Zap },
      { title: "KPI VA OG'ISH", url: "", icon: Target, separator: true },
      { title: "OEE Monitor", url: "pp/oee-monitor", icon: Gauge },
      { title: "KPI va Og'ish", url: "pp/kpi-deviation", icon: Target },
      { title: "Real-time Progress", url: "pp/realtime-progress", icon: Activity },
    ]
  },
  tz07: {
    title: "Ishlab Chiqarish",
    icon: Tablet,
    defaultUrl: "mes/dashboard-home",
    items: [
      { title: "DASHBOARD", url: "", icon: LayoutDashboard, separator: true },
      { title: "MES Dashboard", url: "mes/dashboard-home", icon: LayoutDashboard },
      { title: "IOT PLANSHET", url: "", icon: Tablet, separator: true },
      { title: "IoT Planshet", url: "iot/tablet", icon: Tablet },
      { title: "Kunlik Reja", url: "iot/daily-view", icon: Calendar },
      { title: "ISHLAB CHIQARISH", url: "", icon: Factory, separator: true },
      { title: "Ish Markazlari", url: "mes/work-centers", icon: Factory },
      { title: "Mahsulotlar", url: "mes/products", icon: Package },
      { title: "Buyurtmalar", url: "production/orders", icon: FileSpreadsheet },
      { title: "To'xtashlar", url: "mes/downtimes", icon: AlertTriangle },
      { title: "Xodim Tayinlashlari", url: "mes/workers", icon: Users },
      { title: "OEE Monitoring", url: "mes/oee-monitor", icon: Gauge },
      { title: "Sabablar Logi", url: "mes/reason-log", icon: ScrollText },
      { title: "SMENA", url: "", icon: Users, separator: true },
      { title: "Ishlab Chiqarish Monitor", url: "iot/dashboard", icon: BarChart3 },
      { title: "Zona Boshqaruvi", url: "mes/zone-management", icon: Map },
      { title: "SENSOR VA KAMERA", url: "", icon: Wifi, separator: true },
      { title: "Texnik Xizmat So'rovi", url: "mes/maintenance-request", icon: Wrench },
      { title: "BAHOLASH", url: "", icon: Star, separator: true },
      { title: "Gamifikatsiya", url: "mes/gamification", icon: Trophy },
      { title: "Uskuna Normalari", url: "mes/machine-norms", icon: Settings },
      { title: "Smena Topshirish", url: "mes/smena-handover", icon: Calendar },
      { title: "KAIZEN", url: "", icon: Zap, separator: true },
      { title: "Kaizen Boshqaruvi", url: "kaizen", icon: Zap },
    ]
  },
  tz08: {
    title: "Ombor",
    icon: Package,
    defaultUrl: "wms/overview",
    items: [
      // Arxitektura: ERP = ko'rish/nazorat; amaliyot (kirim/chiqim/qabul) = POS Monitor.
      // Toza kanonik oqim (2026-05-30) — rasvo WMSExtended/Hub/Integratsiya stublari olib tashlandi.
      { title: "NAZORAT (ERP)", url: "", icon: Package, separator: true },
      { title: "Moliya nazorati", url: "wms/overview", icon: DollarSign },
      { title: "Omborlar", url: "wms/warehouses", icon: Boxes },
      { title: "Xarid so'rovi (P2P)", url: "wms/procurement", icon: ShoppingCart },
      { title: "AMALIYOT", url: "", icon: MonitorDot, separator: true },
      { title: "POS Monitor (kirim/chiqim)", url: "pos-monitor", icon: MonitorDot },
      { title: "INVENTAR / HISOBOT", url: "", icon: ClipboardList, separator: true },
      { title: "Inventarizatsiya", url: "wms/inventory", icon: ClipboardCheck },
      { title: "Qabul Akti (GRN)", url: "wms/grn", icon: PackageCheck },
      { title: "Reservation Panel", url: "wms/reservation", icon: Lock },
      { title: "Material 360°", url: "inventory/materials", icon: Package },
      { title: "Tayyor Mahsulot Ijara", url: "wms/rental", icon: DollarSign },
    ]
  },
  tz09: {
    title: "Ta'minot",
    icon: Truck,
    defaultUrl: "mm/dashboard",
    items: [
      { title: "TA'MINOT", url: "", icon: ShoppingCart, separator: true },
      { title: "MM Dashboard", url: "mm/dashboard", icon: BarChart3 },
      { title: "Yetkazuvchilar", url: "mm/vendors", icon: Truck },
      { title: "Xarid Buyurtmalari", url: "mm/purchase-orders", icon: ShoppingCart },
      { title: "PUL NAZORATI", url: "", icon: DollarSign, separator: true },
      { title: "Xarajat Nazorati", url: "integration/expense-management", icon: DollarSign },
      { title: "Chek Bot", url: "mm/check-bot", icon: Zap },
      { title: "Kreditor Qarzlar", url: "mm/creditor-debts", icon: CreditCard },
      { title: "YETKAZUVCHI", url: "", icon: BadgeCheck, separator: true },
      { title: "Yetkazuvchi Baho", url: "integration/vendor-performance", icon: Trophy },
      { title: "Supplier Portal", url: "mm/supplier-portal", icon: Globe },
      { title: "LOGISTIKA", url: "", icon: Navigation, separator: true },
      { title: "Transport Parki", url: "logistics/transport", icon: Car },
      { title: "Marshrut Rejalashtirish", url: "logistics/route-planning", icon: Map },
      { title: "GPS Monitoring", url: "logistics/gps", icon: Navigation },
      { title: "Yoqilg'i Nazorati", url: "logistics/fuel", icon: Fuel },
      { title: "HAYDOVCHI", url: "", icon: UserCog, separator: true },
      { title: "Haydovchi Boshqaruvi", url: "logistics/drivers", icon: UserCog },
      { title: "Mashina Jadvali", url: "logistics/vehicle-schedule", icon: Calendar },
    ]
  },
  tz10: {
    title: "Moliya",
    icon: TrendingUp,
    defaultUrl: "cfo-dashboard",
    items: [
      { title: "GL / IKKI YOQLAMA", url: "", icon: BookOpen, separator: true },
      { title: "CFO", url: "cfo", icon: Crown },
      { title: "CFO Dashboard", url: "cfo-dashboard", icon: BarChart3 },
      { title: "AI Moliya", url: "ai/finance", icon: BrainCircuit },
      { title: "Bosh Buxgalter", url: "finance-dashboard", icon: LayoutDashboard },
      { title: "GL Hujjatlar", url: "accounting/gl-documents", icon: FileText },
      { title: "Hisoblar Rejasi", url: "accounting/chart-of-accounts", icon: BookOpen },
      { title: "Davr Yopish", url: "accounting/period-closing", icon: Calendar },
      { title: "HISOBOTLAR", url: "", icon: FileText, separator: true },
      { title: "Pul Oqimi", url: "finance/cashflow", icon: TrendingUp },
      { title: "Byudjet", url: "finance/budgets", icon: Target },
      { title: "Foyda Tahlili", url: "finance/profitability", icon: BarChart3 },
      { title: "Hisobotlar", url: "finance/reports", icon: FileCheck },
      { title: "DEBITOR / KREDITOR", url: "", icon: Users, separator: true },
      { title: "Debitorlar", url: "accounting/ar", icon: Users },
      { title: "Kreditorlar", url: "accounting/ap", icon: Truck },
      { title: "Moliya Tasdiqlash", url: "finance/approval", icon: CheckCircle },
      { title: "AVANS VA KASSA", url: "", icon: Banknote, separator: true },
      { title: "Kassa", url: "accounting/cash-register", icon: DollarSign },
      { title: "Kirim/Chiqim", url: "accounting/income-expense", icon: TrendingUp },
      // POS Monitor (pos-monitor) = yagona kanonik POS (zavod ombori tablet ilovasi).
      // Eski /pos/* klasteri /pos-monitor'ni takrorlardi; "POS Kassa" → Kassa (yuqorida).
      // 2026-05-21 kanon. Qarang: Qoida 22 + scripts/check-sidebar-regress.mjs.
      { title: "POS TIZIMI", url: "", icon: ShoppingCart, separator: true },
      { title: "POS Monitor", url: "pos-monitor", icon: MonitorDot },
      { title: "Ish Haqi", url: "accounting/payroll-automation", icon: Calculator },
      { title: "TANNARX", url: "", icon: Calculator, separator: true },
      { title: "Buyurtma Tannarxi", url: "finance/order-costing", icon: Calculator },
      { title: "Ombor Hisobi", url: "accounting/materials", icon: Package },
      { title: "Inventarizatsiya", url: "accounting/inventory-valuation", icon: ClipboardCheck },
      { title: "Asosiy Vositalar", url: "accounting/asset-management", icon: Building2 },
      { title: "Xarajat Markazlari", url: "fi/cost-centers", icon: Building2 },
      { title: "Transfer Pricing", url: "fi/transfer-pricing", icon: RotateCcw },
      { title: "SOLIQLAR", url: "", icon: FileSpreadsheet, separator: true },
      { title: "Ichki Soliqlar", url: "fi/tax-management", icon: FileSpreadsheet },
      { title: "Soliq Kalendari", url: "fi/tax-calendar", icon: Calendar },
      { title: "CFO BOSHQARUV", url: "", icon: Crown, separator: true },
      { title: "Audit Log", url: "fi/audit-log", icon: ScrollText },
      { title: "Moliyaviy Risk AI", url: "fi/risk-ai", icon: BrainCircuit },
    ]
  },
  tz11: {
    title: "Xodimlar",
    icon: Users,
    defaultUrl: "hr-dashboard",
    items: [
      { title: "TASHKILOT", url: "", icon: Network, separator: true },
      { title: "HR Dashboard", url: "hr-dashboard", icon: BarChart3 },
      { title: "Org Tuzilma", url: "org-structure/hierarchy", icon: Network },
      { title: "HR Xarita", url: "hr-map", icon: MapPin },
      { title: "REKRUTING", url: "", icon: UserCheck, separator: true },
      { title: "Rekruting Voronka", url: "hr/recruiting", icon: UserCheck },
      { title: "AI Intervyu", url: "ai-hr/interviews", icon: Mic },
      { title: "360° PROFIL", url: "", icon: Users, separator: true },
      { title: "Xodimlar", url: "employees", icon: Users },
      { title: "AI HR Dashboard", url: "ai-hr/dashboard", icon: BrainCircuit },
      { title: "Maqsadlar", url: "goals", icon: Target },
      { title: "DAVOMAT VA SMENA", url: "", icon: Calendar, separator: true },
      { title: "Smena Jadvali", url: "shift-schedule", icon: Calendar },
      { title: "Bildirishnomalar", url: "notifications", icon: Inbox },
      { title: "Aktivlar", url: "assets", icon: Building2 },
      { title: "Ta'til va Kasallik", url: "hr/vacation-sick", icon: HeartPulse },
      { title: "BAHOLASH", url: "", icon: Award, separator: true },
      { title: "Xodim Baholash", url: "integration/employee-rating", icon: Award },
      { title: "Ko'nikmalar Matritsasi", url: "skills-matrix", icon: Target },
      { title: "Mentorlik", url: "mentorship", icon: UserCheck },
      { title: "Succession Planning", url: "hr/succession", icon: RotateCcw },
      { title: "ONBOARDING", url: "", icon: UserPlus, separator: true },
      { title: "Onboarding", url: "hr/onboarding", icon: UserPlus },
      { title: "OFFBOARDING", url: "", icon: UserMinus, separator: true },
      { title: "Offboarding", url: "hr/offboarding", icon: UserMinus },
      { title: "NAZORAT", url: "", icon: ShieldCheck, separator: true },
      { title: "Intizom", url: "discipline", icon: FileText },
      { title: "Sog'liq Nazorati", url: "hr/health-monitoring", icon: HeartPulse },
      { title: "Kasbiy O'sish", url: "hr/career-path", icon: TrendingUp },
      { title: "Xavfsizlik", url: "hr/safety", icon: ShieldCheck },
      { title: "HR V2 TIZIMI", url: "", icon: Award, separator: true },
      { title: "Kunlik Hisobot", url: "hr/daily-reports", icon: ClipboardList },
      { title: "Reception", url: "hr/reception", icon: MapPin },
      { title: "YANGI TIZIMLAR", url: "", icon: Star, separator: true },
      { title: "Referral Tizimi", url: "hr/referrals", icon: UserPlus },
      { title: "HR BREND", url: "", icon: Megaphone, separator: true },
      { title: "HR Brend Boshqaruv", url: "hr/brand", icon: Megaphone },
      { title: "HAFTALIK REJA", url: "", icon: ClipboardList, separator: true },
      { title: "Haftalik Reja", url: "weekly-plan", icon: ClipboardList },
    ]
  },
  tz12: {
    title: "Ta'lim",
    icon: GraduationCap,
    defaultUrl: "lms-dashboard",
    items: [
      { title: "KURSLAR", url: "", icon: BookOpen, separator: true },
      { title: "LMS Dashboard", url: "lms-dashboard", icon: BarChart3 },
      { title: "Kurslar", url: "courses", icon: BookOpen },
      { title: "Darslar", url: "lessons", icon: PlayCircle },
      { title: "HR Capital Testlar", url: "hr-capital/tests", icon: Brain },
      { title: "Kurs Muallifi", url: "lms/course-author", icon: Mic },
      { title: "TESTLAR VA BAHOLASH", url: "", icon: ClipboardList, separator: true },
      { title: "Testlar", url: "tests", icon: ClipboardList },
      { title: "Imtihonlar", url: "all-exams", icon: FileCheck },
      { title: "AI Imtihonlar", url: "ai-exams", icon: BrainCircuit },
      { title: "SERTIFIKAT", url: "", icon: Award, separator: true },
      { title: "Sertifikatlar", url: "certificates", icon: Award },
      { title: "Operator Sertifikatsiyasi", url: "lms/operator-certification", icon: BadgeCheck },
      { title: "Test Boshqaruvi", url: "lms/test-management", icon: ClipboardList },
      { title: "MENTORLIK", url: "", icon: UserCheck, separator: true },
      { title: "Mentorlik", url: "mentorship", icon: UserCheck },
      { title: "GAMIFIKATSIYA", url: "", icon: Trophy, separator: true },
      { title: "Leaderboard", url: "lms/leaderboard", icon: Trophy },
      { title: "BILIM BAZASI", url: "", icon: BookMarked, separator: true },
      { title: "Tadbirlar", url: "events-calendar", icon: Calendar },
      { title: "Bilim Bazasi", url: "lms/knowledge-base", icon: BookMarked },
      { title: "Micro-learning", url: "lms/micro-learning", icon: PlayCircle },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "HR ↔ LMS", url: "integration/hr-lms", icon: GraduationCap },
      { title: "O'quv Byudjeti", url: "lms/learning-budget", icon: DollarSign },
      { title: "Statistika", url: "analytics", icon: BarChart3 },
    ]
  },
  tz13: {
    title: "Xavfsizlik",
    icon: Lock,
    defaultUrl: "camera-safety",
    items: [
      { title: "KIRISH NAZORATI", url: "", icon: Fingerprint, separator: true },
      { title: "Xavfsizlik Holati", url: "camera-safety", icon: ShieldCheck },
      { title: "Yuz Tanish Kuzatuv", url: "camera/monitoring", icon: ScanLine },
      { title: "Yuz Ro'yxatdan O'tish", url: "face-registration", icon: UserCog },
      { title: "Davomat", url: "security/attendance", icon: UserCheck },
      { title: "Zona Ruxsatlari", url: "security/zone-access", icon: Lock },
      { title: "KAMERA", url: "", icon: Camera, separator: true },
      { title: "Jonli Monitoring", url: "camera-live-monitoring", icon: Camera },
      { title: "Kameralar", url: "cameras", icon: Camera },
      { title: "Hodisalar", url: "camera-alerts", icon: AlertTriangle },
      { title: "HODISALAR VA XAVF", url: "", icon: HardHat, separator: true },
      { title: "PPE Nazorati", url: "security/ppe", icon: HardHat },
      { title: "Xavfli Material", url: "security/hazmat", icon: AlertTriangle },
      { title: "Evakuatsiya Rejasi", url: "security/evacuation", icon: Flame },
      { title: "REYTING", url: "", icon: Star, separator: true },
      { title: "Tashrif Nazorati", url: "security/visitors", icon: UserCheck },
      { title: "Xavfsizlik Reytingi", url: "security/rating", icon: Star },
    ]
  },
  tz14: {
    title: "Xo'jalik",
    icon: Wrench,
    defaultUrl: "mro/dashboard",
    items: [
      { title: "TEXNIK XIZMAT", url: "", icon: Wrench, separator: true },
      { title: "MRO Dashboard", url: "mro/dashboard", icon: BarChart3 },
      { title: "Ta'mirlash Buyurtmalari", url: "integration/mro", icon: Wrench },
      { title: "Preventive Maintenance", url: "mro/preventive", icon: Calendar },
      { title: "MRO Ehtiyot Qismlar", url: "mro/spare-parts", icon: Settings },
      { title: "KOMMUNAL", url: "", icon: Zap, separator: true },
      { title: "Elektr/Gaz/Suv", url: "mro/utilities", icon: Zap },
      { title: "Xarajat Nazorati", url: "mro/expense-control", icon: DollarSign },
      { title: "XO'JALIK", url: "", icon: Briefcase, separator: true },
      { title: "Oshxona va Ovqat", url: "mro/kitchen", icon: UtensilsCrossed },
      { title: "Forma Boshqaruvi", url: "mro/uniforms", icon: Shirt },
      { title: "Ofis Inventari", url: "mro/office-inventory", icon: Package },
      { title: "MUHIT", url: "", icon: Recycle, separator: true },
      { title: "Tozalash Xizmati", url: "mro/cleaning", icon: Droplets },
      { title: "Chiqindi Nazorati", url: "europrint/waste-tracking", icon: Recycle },
      { title: "Sanitariya", url: "mro/sanitation", icon: ShieldCheck },
      { title: "Bino Inventari", url: "mro/building-inventory", icon: Building2 },
    ]
  },
  tz15: {
    title: "IoT va Kamera",
    icon: Cpu,
    defaultUrl: "camera-dashboard",
    items: [
      { title: "IOT SENSORLAR", url: "", icon: Wifi, separator: true },
      { title: "IoT Dashboard", url: "iot/dashboard", icon: Radio },
      { title: "Sensor Monitoring", url: "iot/sensor-monitoring", icon: Thermometer },
      { title: "Mashina Holati", url: "camera-machines", icon: Factory },
      { title: "KAMERALAR", url: "", icon: Camera, separator: true },
      { title: "Kamera Dashboard", url: "camera-dashboard", icon: BarChart3 },
      { title: "Kameralar", url: "cameras", icon: Camera },
      { title: "Issiqlik Xaritasi", url: "camera-heatmap", icon: MapPin },
      { title: "AI TAHLIL", url: "", icon: BrainCircuit, separator: true },
      { title: "AI Nazorat Hub", url: "camera-ai", icon: BrainCircuit },
      { title: "Sifat Nazorati", url: "camera-quality", icon: FileCheck },
      { title: "Xodim Monitoring", url: "camera-employees", icon: Users },
      { title: "Xodim Reytingi", url: "camera-employee-ratings", icon: Trophy },
      { title: "AI Sozlamalar", url: "camera-settings", icon: Settings },
      { title: "TEXNIK", url: "", icon: Gauge, separator: true },
      { title: "Predictive Maintenance", url: "iot/predictive-maintenance", icon: MonitorDot },
      { title: "OEE Live", url: "iot/oee-live", icon: Gauge },
      { title: "Digital Twin", url: "iot/digital-twin", icon: Database },
      { title: "Ogohlantirishlar", url: "iot/alerts", icon: AlertTriangle },
      { title: "Hisobotlar", url: "camera-reports", icon: FileText },
    ]
  },
  tz16: {
    title: "Direktor",
    icon: Crown,
    defaultUrl: "europrint/director",
    items: [
      { title: "UMUMIY PANEL", url: "", icon: Crown, separator: true },
      { title: "Direktor Dashboard", url: "europrint/director", icon: Crown },
      { title: "AIsha (AI Yordamchi)", url: "aisha", icon: Sparkles },
      { title: "Nazorat Markazi", url: "europrint/control", icon: ShieldCheck },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "Auditor Panel", url: "europrint/auditor", icon: FileCheck },
      { title: "Buxgalter Ko'rinishi", url: "europrint/accountant", icon: DollarSign },
      { title: "Kunlik KPI", url: "finance/daily-kpi", icon: Activity },
      { title: "Kunlik KPI Baholash", url: "europrint/employee-kpi", icon: Activity },
      { title: "BOSHQARUV", url: "", icon: Settings, separator: true },
      { title: "Strategik Rejalashtirish", url: "europrint/strategic", icon: Rocket },
      { title: "Hisobotlar Markazi", url: "europrint/reports-hub", icon: FileText },
      { title: "AI Xulosa", url: "director/ai-summary", icon: BrainCircuit },
      { title: "Muammoli Nuqtalar", url: "director/problem-points", icon: AlertTriangle },
      { title: "AI AGENTLAR", url: "", icon: BrainCircuit, separator: true },
      { title: "14 AI Agent Hub", url: "agents", icon: BrainCircuit },
      { title: "Ishlab Chiqarish Agent", url: "agents/production", icon: Factory },
      { title: "HR Agent", url: "agents/hr-performance", icon: Users },
      { title: "Sifat Agent", url: "agents/quality", icon: CheckCircle },
      { title: "Strategik Agent", url: "agents/strategic", icon: Target },
      { title: "Xo'jalik Agent", url: "agents/facilities", icon: Wrench },
      { title: "IDEAL RASM", url: "", icon: Target, separator: true },
      { title: "Ideal Rasm", url: "ideal-rasm", icon: Target },
    ]
  },
  tz17: {
    title: "Admin Panel",
    icon: Globe,
    defaultUrl: "super-admin",
    items: [
      { title: "TENANTLAR", url: "", icon: Database, separator: true },
      { title: "Super Admin Panel", url: "super-admin", icon: Crown },
      { title: "Tenant Boshqaruvi", url: "saas/tenant-management", icon: Database },
      { title: "Yangi Zavod Onboarding", url: "saas/onboarding", icon: Rocket },
      { title: "LITSENZIYA", url: "", icon: Key, separator: true },
      { title: "Litsenziya va Tariflar", url: "saas/licensing", icon: Key },
      { title: "Modul Yoqish/O'chirish", url: "saas/module-control", icon: PanelLeftClose },
      { title: "TIZIM", url: "", icon: Server, separator: true },
      { title: "Monitoring", url: "saas/monitoring", icon: MonitorDot },
      { title: "Xatolar Logi", url: "saas/error-log", icon: Bug },
      { title: "Istisno Holatlar", url: "admin/exceptions", icon: AlertTriangle },
      { title: "Navbat Monitori", url: "admin/queues", icon: Activity },
      { title: "Arizalar", url: "applications", icon: FileText },
      { title: "Sozlamalar", url: "settings", icon: Settings },
      { title: "TELEGRAM", url: "", icon: MessageSquare, separator: true },
      { title: "Telegram Admin", url: "telegram/admin", icon: MessageSquare },
    ]
  },
  kanban: {
    title: "Vazifalar",
    icon: FolderKanban,
    defaultUrl: "kanban",
    items: [
      { title: "KANBAN", url: "", icon: FolderKanban, separator: true },
      { title: "Buyurtmalar Kanbani", url: "kanban", icon: FolderKanban },
      { title: "Rekruting Kanbani", url: "hr/recruiting-kanban", icon: UserCheck },
      { title: "Strategik Vazifalar", url: "strategic-tasks", icon: Target },
      { title: "Ilovalar", url: "applications", icon: FileText },
    ]
  },
  coordination: {
    title: "Koordinatsiya",
    icon: Network,
    defaultUrl: "coordination",
    items: [
      { title: "KOORDINATSIYA", url: "", icon: Network, separator: true },
      { title: "Kommunikatsiya Markazi", url: "coordination?tab=baskets", icon: Inbox },
      { title: "5 Kengash Tizimi", url: "coordination?tab=councils", icon: Network },
      { title: "Hisobot Yuborish", url: "coordination?tab=dokla", icon: Rocket },
      { title: "Ko'rsatma Berish", url: "coordination?tab=raspo", icon: Crown },
      { title: "AI AGENTLAR", url: "", icon: BrainCircuit, separator: true },
      { title: "AI Agentlar (14 ta)", url: "agents", icon: BrainCircuit },
      { title: "Production AI", url: "agents/production", icon: Factory },
      { title: "HR AI", url: "agents/hr-performance", icon: Users },
      { title: "Quality AI", url: "agents/quality", icon: CheckCircle },
      { title: "Strategic AI", url: "agents/strategic", icon: Target },
      { title: "Facilities AI", url: "agents/facilities", icon: Wrench },
      { title: "Procurement AI", url: "agents/procurement", icon: Truck },
    ]
  },
  chat: {
    title: "Chat",
    icon: MessageSquare,
    defaultUrl: "chat",
    items: [
      { title: "ICHKI CHAT", url: "", icon: MessageSquare, separator: true },
      { title: "Xabarlar", url: "chat", icon: MessageSquare },
      { title: "To'g'ridan-to'g'ri", url: "chat", icon: Users },
      { title: "Guruhlar", url: "chat", icon: Users },
      { title: "Kanallar", url: "chat", icon: Megaphone },
    ]
  },
};

  export const moduleColors: Record<string, { bg: string; text: string; activeBg: string; border: string }> = {
  tz01: { bg: "bg-blue-500/10 hover:bg-blue-500/20", text: "text-blue-600 dark:text-blue-400", activeBg: "bg-blue-500 text-white", border: "border-blue-500/30" },
  tz02: { bg: "bg-orange-500/10 hover:bg-orange-500/20", text: "text-orange-600 dark:text-orange-400", activeBg: "bg-orange-500 text-white", border: "border-orange-500/30" },
  tz03: { bg: "bg-pink-500/10 hover:bg-pink-500/20", text: "text-pink-600 dark:text-pink-400", activeBg: "bg-pink-500 text-white", border: "border-pink-500/30" },
  tz04: { bg: "bg-teal-500/10 hover:bg-teal-500/20", text: "text-teal-600 dark:text-teal-400", activeBg: "bg-teal-500 text-white", border: "border-teal-500/30" },
  tz05: { bg: "bg-lime-500/10 hover:bg-lime-500/20", text: "text-lime-600 dark:text-lime-400", activeBg: "bg-lime-500 text-white", border: "border-lime-500/30" },
  tz06: { bg: "bg-amber-500/10 hover:bg-amber-500/20", text: "text-amber-600 dark:text-amber-400", activeBg: "bg-amber-500 text-white", border: "border-amber-500/30" },
  tz07: { bg: "bg-purple-500/10 hover:bg-purple-500/20", text: "text-purple-600 dark:text-purple-400", activeBg: "bg-purple-500 text-white", border: "border-purple-500/30" },
  tz08: { bg: "bg-emerald-500/10 hover:bg-emerald-500/20", text: "text-emerald-600 dark:text-emerald-400", activeBg: "bg-emerald-500 text-white", border: "border-emerald-500/30" },
  tz09: { bg: "bg-green-500/10 hover:bg-green-500/20", text: "text-green-600 dark:text-green-400", activeBg: "bg-green-500 text-white", border: "border-green-500/30" },
  tz10: { bg: "bg-indigo-500/10 hover:bg-indigo-500/20", text: "text-indigo-600 dark:text-indigo-400", activeBg: "bg-indigo-500 text-white", border: "border-indigo-500/30" },
  tz11: { bg: "bg-rose-500/10 hover:bg-rose-500/20", text: "text-rose-600 dark:text-rose-400", activeBg: "bg-rose-500 text-white", border: "border-rose-500/30" },
  tz12: { bg: "bg-violet-500/10 hover:bg-violet-500/20", text: "text-violet-600 dark:text-violet-400", activeBg: "bg-violet-500 text-white", border: "border-violet-500/30" },
  tz13: { bg: "bg-red-500/10 hover:bg-red-500/20", text: "text-red-600 dark:text-red-400", activeBg: "bg-red-500 text-white", border: "border-red-500/30" },
  tz14: { bg: "bg-stone-500/10 hover:bg-stone-500/20", text: "text-stone-600 dark:text-stone-400", activeBg: "bg-stone-500 text-white", border: "border-stone-500/30" },
  tz15: { bg: "bg-cyan-500/10 hover:bg-cyan-500/20", text: "text-cyan-600 dark:text-cyan-400", activeBg: "bg-cyan-500 text-white", border: "border-cyan-500/30" },
  tz16: { bg: "bg-yellow-500/10 hover:bg-yellow-500/20", text: "text-yellow-600 dark:text-yellow-400", activeBg: "bg-yellow-600 text-white", border: "border-yellow-500/30" },
  tz17: { bg: "bg-slate-500/10 hover:bg-slate-500/20", text: "text-slate-600 dark:text-slate-400", activeBg: "bg-slate-600 text-white", border: "border-slate-500/30" },
  kanban: { bg: "bg-fuchsia-500/10 hover:bg-fuchsia-500/20", text: "text-fuchsia-600 dark:text-fuchsia-400", activeBg: "bg-fuchsia-600 text-white", border: "border-fuchsia-500/30" },
  coordination: { bg: "bg-sky-500/10 hover:bg-sky-500/20", text: "text-sky-600 dark:text-sky-400", activeBg: "bg-sky-600 text-white", border: "border-sky-500/30" },
  chat: { bg: "bg-blue-500/10 hover:bg-blue-500/20", text: "text-blue-600 dark:text-blue-400", activeBg: "bg-blue-600 text-white", border: "border-blue-500/30" },
};

  export const MODULE_PERMISSION_KEYS: Record<string, string> = {
  tz01: "CRM",
  tz02: "MARKETING",
  tz03: "DESIGN",
  tz04: "QC",
  tz05: "PRODUCTION",
  tz06: "PRODUCTION",
  tz07: "PRODUCTION",
  tz08: "WAREHOUSE",
  tz09: "LOGISTICS",
  tz10: "FINANCE",
  tz11: "HR",
  tz12: "LMS",
  tz13: "SECURITY",
  tz14: "MRO",
  tz15: "IOT",
  tz16: "REPORTS",
  tz17: "USERS",
  kanban: "OKR",
  coordination: "DIRECTOR",
};

  export const moduleAccentColors: Record<string, string> = {
  tz01: "bg-blue-700", tz02: "bg-orange-600", tz03: "bg-pink-600",
  tz04: "bg-teal-600", tz05: "bg-lime-600", tz06: "bg-amber-600",
  tz07: "bg-purple-700", tz08: "bg-emerald-600", tz09: "bg-green-600",
  tz10: "bg-indigo-700", tz11: "bg-rose-600", tz12: "bg-violet-700",
  tz13: "bg-red-600", tz14: "bg-stone-600", tz15: "bg-cyan-600",
  tz16: "bg-yellow-600", tz17: "bg-slate-600", kanban: "bg-fuchsia-700",
  coordination: "bg-sky-600", chat: "bg-blue-600",
};

  export function getTranslatedMenuGroups(t: (key: string) => string): Record<string, MenuGroup> {
    const groups = menuGroups as Record<string, MenuGroup>;
    const hrModule = groups.tz11;

    // Marketing (tz02) backend has ~60/99 endpoints returning 501. Hide the
    // entire module from the sidebar unless the build explicitly opts in via
    // VITE_FEATURE_MARKETING=true. See artifacts/erp-dashboard/src/lib/feature-flags.ts.
    let next: Record<string, MenuGroup> = groups;
    if (!FEATURE_MARKETING) {
      const { tz02: _omitted, ...rest } = next;
      void _omitted;
      next = rest;
    }
    if (!hrModule) return next;
    return { ...next, tz11: translateHrModule(t, hrModule) };
  }

  export function findModuleByPath(path: string): string | null {
    const cleanPath = path.startsWith("/") ? path.slice(1) : path;

    for (const [moduleKey, group] of Object.entries(menuGroups)) {
      if (group.defaultUrl && (cleanPath === group.defaultUrl || cleanPath.startsWith(group.defaultUrl + "/"))) {
        return moduleKey;
      }
      for (const item of group.items) {
        if (!("separator" in item) || !item.separator) {
          if (item.url && (cleanPath === item.url || cleanPath.startsWith(item.url + "/"))) {
            return moduleKey;
          }
        }
      }
    }

    return null;
  }
  