/** @module constants-admin-coord @description Sidebar navigation constants for Director (tz16), Admin/SaaS (tz17), Kanban, Coordination, and Chat modules. */

import {
  Crown, ShieldCheck, BarChart3, FileCheck, DollarSign, Activity,
  Rocket, FileText, BrainCircuit, AlertTriangle, Target, Settings,
  Database, Key, PanelLeftClose, Server, MonitorDot, Bug, MessageSquare,
  FolderKanban, UserCheck, Network, Inbox, Megaphone, Users,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsAdminCoord: Record<string, MenuGroup> = {
  tz16: {
    title: "Direktor",
    icon: Crown,
    defaultUrl: "europrint/director",
    items: [
      { title: "UMUMIY PANEL", url: "", icon: Crown, separator: true },
      { title: "Direktor Dashboard", url: "europrint/director", icon: Crown },
      { title: "Nazorat Markazi", url: "europrint/control", icon: ShieldCheck },
      { title: "TAHLIL", url: "", icon: BarChart3, separator: true },
      { title: "Auditor Panel", url: "europrint/auditor", icon: FileCheck },
      { title: "Buxgalter Ko'rinishi", url: "europrint/accountant", icon: DollarSign },
      { title: "Kunlik KPI", url: "finance/daily-kpi", icon: Activity },
      { title: "Kunlik KPI Baholash", url: "europrint/employee-kpi", icon: Activity },
      { title: "BOSHQARUV", url: "", icon: Settings, separator: true },
      { title: "Strategik Rejalashtirish", url: "europrint/strategic", icon: Rocket },
      { title: "Hisobotlar Markazi", url: "europrint/reports-hub", icon: FileText },
      { title: "AI Xulosa", url: "director/ai-summary", icon: BrainCircuit },
      { title: "Muammoli Nuqtalar", url: "director/problem-points", icon: AlertTriangle },
      { title: "IDEAL RASM", url: "", icon: Target, separator: true },
      { title: "Ideal Rasm", url: "ideal-rasm", icon: Target },
    ],
  },
  tz17: {
    title: "Admin Panel",
    icon: Database,
    defaultUrl: "super-admin",
    items: [
      { title: "TENANTLAR", url: "", icon: Database, separator: true },
      { title: "Super Admin Panel", url: "super-admin", icon: Crown },
      { title: "Tenant Boshqaruvi", url: "saas/tenant-management", icon: Database },
      { title: "Yangi Zavod Onboarding", url: "saas/onboarding", icon: Rocket },
      { title: "LITSENZIYA", url: "", icon: Key, separator: true },
      { title: "Litsenziya va Tariflar", url: "saas/licensing", icon: Key },
      { title: "Modul Yoqish/O'chirish", url: "saas/module-control", icon: PanelLeftClose },
      { title: "TIZIM", url: "", icon: Server, separator: true },
      { title: "Monitoring", url: "saas/monitoring", icon: MonitorDot },
      { title: "Xatolar Logi", url: "saas/error-log", icon: Bug },
      { title: "Istisno Holatlar", url: "admin/exceptions", icon: AlertTriangle },
      { title: "Navbat Monitori", url: "admin/queues", icon: Activity },
      { title: "Arizalar", url: "applications", icon: FileText },
      { title: "Sozlamalar", url: "settings", icon: Settings },
      { title: "TELEGRAM", url: "", icon: MessageSquare, separator: true },
      { title: "Telegram Admin", url: "telegram/admin", icon: MessageSquare },
    ],
  },
  kanban: {
    title: "Vazifalar",
    icon: FolderKanban,
    defaultUrl: "kanban",
    items: [
      { title: "KANBAN", url: "", icon: FolderKanban, separator: true },
      { title: "Buyurtmalar Kanbani", url: "kanban", icon: FolderKanban },
      { title: "Rekruting Kanbani", url: "hr/recruiting-kanban", icon: UserCheck },
      { title: "Strategik Vazifalar", url: "strategic-tasks", icon: Target },
      { title: "Ilovalar", url: "applications", icon: FileText },
    ],
  },
  coordination: {
    title: "Koordinatsiya",
    icon: Network,
    defaultUrl: "coordination",
    items: [
      { title: "KOORDINATSIYA", url: "", icon: Network, separator: true },
      { title: "Kommunikatsiya Markazi", url: "coordination?tab=baskets", icon: Inbox },
      { title: "AI Agentlar (14 ta)", url: "agents", icon: Network },
      { title: "Production AI",  url: "agents/production",      icon: Network },
      { title: "HR AI",          url: "agents/hr-performance",  icon: Network },
      { title: "Quality AI",     url: "agents/quality",         icon: Network },
      { title: "Strategic AI",   url: "agents/strategic",       icon: Network },
      { title: "Facilities AI",  url: "agents/facilities",      icon: Network },
      { title: "Procurement AI", url: "agents/procurement",     icon: Network },
      { title: "5 Kengash Tizimi", url: "coordination?tab=councils", icon: Network },
      { title: "Hisobot Yuborish", url: "coordination?tab=dokla", icon: Rocket },
      { title: "Ko'rsatma Berish", url: "coordination?tab=raspo", icon: Crown },
    ],
  },
  chat: {
    title: "Chat",
    icon: MessageSquare,
    defaultUrl: "chat",
    items: [
      { title: "ICHKI CHAT", url: "", icon: MessageSquare, separator: true },
      { title: "Xabarlar", url: "chat", icon: MessageSquare },
      { title: "To'g'ridan-to'g'ri", url: "chat", icon: Users },
      { title: "Guruhlar", url: "chat", icon: Users },
      { title: "Kanallar", url: "chat", icon: Megaphone },
    ],
  },
};
