/** @module constants-hidden
 * @description "Yashirin sahifalar" moduli — routed bo'lib lekin sidebar'da yo'q
 * sahifalar. Foydalanuvchi (IT direktor) bularni ko'rib chiqib, bittalab
 * o'chiradi yoki keraklisini boshqa modulga ko'chiradi.
 *
 * AUTO-GENERATED — to regenerate: `node gen-hidden.mjs`.
 */

import {
  Eye, Users, Store, ShoppingCart, Warehouse, BrainCircuit, Crown, DollarSign,
  Plug, Settings, BookOpen, Building, Factory, CheckSquare, Printer, FileText,
} from "lucide-react";
import { MenuGroup } from "./types";

export const menuGroupsHidden: Record<string, MenuGroup> = {
  hidden: {
    title: "🔍 Yashirin sahifalar",
    icon: Eye,
    defaultUrl: "hr/face-employees",
    items: [
      { title: "HR — 10 ta", url: "", icon: Users, separator: true },
      { title: "Employees For Face", url: "hr/face-employees", icon: Users },
      { title: "H R Succession Planning", url: "hr/succession-planning", icon: Users },
      { title: "Recruiter K P I", url: "hr/recruiter-kpi", icon: Users },
      { title: "Peer Review", url: "hr/peer-review", icon: Users },
      { title: "Candidate Report", url: "hr/candidate-report/", icon: Users },
      { title: "Inspection", url: "hr/inspection", icon: Users },
      { title: "Internal Job Board", url: "hr/internal-jobs", icon: Users },
      { title: "H R Vacation Sick", url: "hr/leave", icon: Users },
      { title: "H R Zno", url: "hr/zno", icon: Users },
      { title: "H R Zvs", url: "hr/zvs", icon: Users },
      { title: "POS — 10 ta", url: "", icon: Store, separator: true },
      { title: "Pos Stock", url: "pos/stock", icon: Store },
      { title: "Pos Warehouse", url: "pos/warehouse", icon: Store },
      { title: "Pos Warehouse", url: "pos/wh", icon: Store },
      { title: "Pos Sync", url: "pos/sync", icon: Store },
      { title: "P O S Dashboard", url: "pos/mini-app", icon: Store },
      { title: "Stub", url: "pos/printer-config", icon: Store },
      { title: "Pos Barc", url: "pos/barcode", icon: Store },
      { title: "Pos Inventory Counts", url: "pos/inventory-counts", icon: Store },
      { title: "Pos Movements", url: "pos/movements", icon: Store },
      { title: "Pos Requests", url: "pos/requests", icon: Store },
      { title: "SAVDO — 10 ta", url: "", icon: ShoppingCart, separator: true },
      { title: "S D Quotations", url: "sd/quotations", icon: ShoppingCart },
      { title: "S D Europrint", url: "sd/crm", icon: ShoppingCart },
      { title: "S D Sales Management", url: "sd/sales-management", icon: ShoppingCart },
      { title: "S D Sales Management", url: "sd/invoices", icon: ShoppingCart },
      { title: "S D Sales Management", url: "sd/forecast", icon: ShoppingCart },
      { title: "S D Sales Management", url: "sd/analytics", icon: ShoppingCart },
      { title: "S D Sales Management", url: "sd/commission", icon: ShoppingCart },
      { title: "S D Debitors", url: "sd/debitors", icon: ShoppingCart },
      { title: "S D Overview Dashboard", url: "sd/dashboard/overview", icon: ShoppingCart },
      { title: "S D Quota Dashboard", url: "sd/dashboard/quota", icon: ShoppingCart },
      { title: "WMS — 9 ta", url: "", icon: Warehouse, separator: true },
      { title: "Goods Receiving", url: "wms/grn", icon: Warehouse },
      { title: "Stock Reservation", url: "wms/reservation", icon: Warehouse },
      { title: "W M S Extended", url: "wms/lot-traceability", icon: Warehouse },
      { title: "W M S Extended", url: "wms/kpi", icon: Warehouse },
      { title: "W M S Dashboard", url: "wms/dashboard", icon: Warehouse },
      { title: "Wms Analytics", url: "wms/analytics", icon: Warehouse },
      { title: "Warehouse Reports All", url: "wms/reports-all", icon: Warehouse },
      { title: "Warehouse Material360", url: "wms/material/360/", icon: Warehouse },
      { title: "Barcode Scanner", url: "wms/scanner", icon: Warehouse },
      { title: "AI — 7 ta", url: "", icon: BrainCircuit, separator: true },
      { title: "A I Agents", url: "ai/agents", icon: BrainCircuit },
      { title: "Forecast Analytics", url: "ai/forecast", icon: BrainCircuit },
      { title: "Agents Hub", url: "ai", icon: BrainCircuit },
      { title: "H R A I Dashboard", url: "ai/hr", icon: BrainCircuit },
      { title: "Ai Crm", url: "ai/marketing", icon: BrainCircuit },
      { title: "Wms Analytics", url: "ai/wms", icon: BrainCircuit },
      { title: "Ai Automation", url: "ai/automation", icon: BrainCircuit },
      { title: "OMBOR — 7 ta", url: "", icon: Warehouse, separator: true },
      { title: "Barcode Warehouse", url: "warehouse/barcode-ops", icon: Warehouse },
      { title: "Inventory Count", url: "warehouse/inventory-count", icon: Warehouse },
      { title: "Goods Receiving", url: "warehouse/goods-receiving", icon: Warehouse },
      { title: "Stock Reservation", url: "warehouse/reservations", icon: Warehouse },
      { title: "Warehouse Reports", url: "warehouse/reports", icon: Warehouse },
      { title: "Barcode System", url: "warehouse/barcodes", icon: Warehouse },
      { title: "Warehouse Integrations", url: "warehouse/integrations", icon: Warehouse },
      { title: "CRM — 6 ta", url: "", icon: Users, separator: true },
      { title: "Crm Funnel Analytics", url: "crm/funnel", icon: Users },
      { title: "Crm Rfm Clusters", url: "crm/rfm", icon: Users },
      { title: "Crm Cohort Analysis", url: "crm/cohort", icon: Users },
      { title: "C R M Activities", url: "crm/activities", icon: Users },
      { title: "C R M Settings", url: "crm/settings", icon: Users },
      { title: "Customer360", url: "crm/customer/", icon: Users },
      { title: "DIREKTOR — 5 ta", url: "", icon: Crown, separator: true },
      { title: "Director Extended", url: "director/production", icon: Crown },
      { title: "Director Extended", url: "director/hr-stats", icon: Crown },
      { title: "Director Extended", url: "director/finance", icon: Crown },
      { title: "Director Extended", url: "director/kpis", icon: Crown },
      { title: "Director Ai Audit", url: "director/ai-audit", icon: Crown },
      { title: "MOLIYA — 4 ta", url: "", icon: DollarSign, separator: true },
      { title: "G L Chart Of Accounts", url: "finance/gl-chart-of-accounts", icon: DollarSign },
      { title: "Finance Variance", url: "finance/variance", icon: DollarSign },
      { title: "Finance Break Even", url: "finance/break-even", icon: DollarSign },
      { title: "Pricing Tiers", url: "finance/pricing-tiers", icon: DollarSign },
      { title: "INTEGRATSIYA — 3 ta", url: "", icon: Plug, separator: true },
      { title: "G L Posting Monitor", url: "integration/gl-posting", icon: Plug },
      { title: "Invoice Verification", url: "integration/invoice-verification", icon: Plug },
      { title: "Integration Management", url: "integration/requests", icon: Plug },
      { title: "ADMIN — 2 ta", url: "", icon: Settings, separator: true },
      { title: "Audit Log", url: "admin/audit-log", icon: Settings },
      { title: "Validate", url: "admin/validate", icon: Settings },
      { title: "TA'LIM — 2 ta", url: "", icon: BookOpen, separator: true },
      { title: "L M S Extended", url: "lms/gamification", icon: BookOpen },
      { title: "L M S Support", url: "lms/support", icon: BookOpen },
      { title: "KURSLAR — 2 ta", url: "", icon: BookOpen, separator: true },
      { title: "Lesson Player", url: "courses//lessons", icon: BookOpen },
      { title: "Lesson Player", url: "courses//lessons/", icon: BookOpen },
      { title: "ERP — 2 ta", url: "", icon: Building, separator: true },
      { title: "Sales Orders", url: "erp/sales", icon: Building },
      { title: "Employee Profile", url: "erp/employee/", icon: Building },
      { title: "CFO — 2 ta", url: "", icon: DollarSign, separator: true },
      { title: "C F O Dashboard", url: "cfo/dashboard", icon: DollarSign },
      { title: "Cfo Config Settings", url: "cfo/config", icon: DollarSign },
      { title: "PP — 2 ta", url: "", icon: Factory, separator: true },
      { title: "Mrp Matrix", url: "pp/mrp", icon: Factory },
      { title: "Crp", url: "pp/crp", icon: Factory },
      { title: "QC — 2 ta", url: "", icon: CheckSquare, separator: true },
      { title: "Q C Dashboard", url: "qc/dashboard-home", icon: CheckSquare },
      { title: "Paper Parameters", url: "qc/paper-parameters", icon: CheckSquare },
      { title: "PRINT — 2 ta", url: "", icon: Printer, separator: true },
      { title: "Ink Coverage Calculator", url: "print/ink-coverage", icon: Printer },
      { title: "Imposition Calculator", url: "print/imposition", icon: Printer },
      { title: "360 — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Customer360", url: "360", icon: FileText },
      { title: "SYSTEM-MONITOR — 1 ta", url: "", icon: FileText, separator: true },
      { title: "System Monitor", url: "system-monitor", icon: FileText },
      { title: "TELEGRAM-BOT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Telegram Bot Admin", url: "telegram-bot", icon: FileText },
      { title: "APPROVALS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Approval Hub", url: "approvals", icon: FileText },
      { title: "INTEGRATIONS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Integration Management", url: "integrations", icon: FileText },
      { title: "CUSTOMER-PORTAL — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Customer Portal Config", url: "customer-portal", icon: FileText },
      { title: "ORDERS-REGISTRY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Orders Registry", url: "orders-registry", icon: FileText },
      { title: "DASHBOARD — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Progress", url: "dashboard/progress", icon: FileText },
      { title: "KNOWLEDGE-BASE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Knowledge Base", url: "knowledge-base", icon: FileText },
      { title: "AI-CRM — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Ai Crm", url: "ai-crm", icon: FileText },
      { title: "ATTENDANCE-MONITOR — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Attendance Monitor", url: "attendance-monitor", icon: FileText },
      { title: "EMPLOYEE-TRACKING — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Employee Tracking Report", url: "employee-tracking", icon: FileText },
      { title: "EUROPRINT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Camera A I Analytics", url: "europrint/camera-ai-analytics", icon: FileText },
      { title: "SECURITY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Security Dashboard", url: "security", icon: FileText },
      { title: "COORDINATION — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Coordination", url: "coordination", icon: FileText },
      { title: "ERP-DAILY-REPORTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "E R P Daily Reports", url: "erp-daily-reports", icon: FileText },
      { title: "ORG-CHART — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Org Chart", url: "org-chart", icon: FileText },
      { title: "ADAPTATION — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Adaptation", url: "adaptation", icon: FileText },
      { title: "BUSINESS-HEALTH — 1 ta", url: "", icon: FileText, separator: true },
      { title: "R A C I Matrix", url: "business-health", icon: FileText },
      { title: "ORG-STRUCTURE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Org Node Detail", url: "org-structure/hierarchy/node/", icon: FileText },
      { title: "ERP-PRODUCTION — 1 ta", url: "", icon: FileText, separator: true },
      { title: "E R P Production", url: "erp-production", icon: FileText },
      { title: "ORDER-APPROVAL — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Order Approval Workflow", url: "order-approval", icon: FileText },
      { title: "TECHNOLOGY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Technology", url: "technology", icon: FileText },
      { title: "TECH — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Tech Dashboard", url: "tech/dashboard-home", icon: FileText },
      { title: "TECH-APPROVAL — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Tech Approval", url: "tech-approval", icon: FileText },
      { title: "TECH-CARDS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Tech Cards", url: "tech-cards", icon: FileText },
      { title: "QC-MODULE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Q C Module", url: "qc-module", icon: FileText },
      { title: "DESIGN-ORDERS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Design Order Detail", url: "design-orders/", icon: FileText },
      { title: "IOT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Warehouse Material Kits", url: "iot/material-kits", icon: FileText },
      { title: "AI-CAMERA — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Camera A I Analytics", url: "ai-camera", icon: FileText },
      { title: "AI-EXAM — 1 ta", url: "", icon: FileText, separator: true },
      { title: "A I Exams", url: "ai-exam", icon: FileText },
      { title: "AI-PLANNING — 1 ta", url: "", icon: FileText, separator: true },
      { title: "A I Production Planning", url: "ai-planning", icon: FileText },
      { title: "ASSIGNMENTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "M E S Worker Assignments", url: "assignments", icon: FileText },
      { title: "INSIGHTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Analytics", url: "insights", icon: FileText },
      { title: "INVENTORY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "P O S Inventory", url: "inventory/advanced", icon: FileText },
      { title: "IOT-ENHANCED — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Io T Extended", url: "iot-enhanced", icon: FileText },
      { title: "VIDEO-PROGRESS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Lesson Player", url: "video-progress", icon: FileText },
      { title: "AUTH — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "auth", icon: FileText },
      { title: "EXPORT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "export", icon: FileText },
      { title: "GPT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "gpt", icon: FileText },
      { title: "MICRO-MODULES — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "micro-modules", icon: FileText },
      { title: "MODULES — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "modules", icon: FileText },
      { title: "SAP — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "sap", icon: FileText },
      { title: "V2 — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Stub", url: "v2/pos/printer-config", icon: FileText },
      { title: "3WAY-MATCH — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Three Way Match", url: "3way-match", icon: FileText },
      { title: "ACHIEVEMENTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Achievements", url: "achievements", icon: FileText },
      { title: "APPLICATION-RESPONSES — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Application Responses", url: "application-responses", icon: FileText },
      { title: "APPROVAL-WORKFLOW — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Approval Workflow", url: "approval-workflow", icon: FileText },
      { title: "ATTEMPTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Attempts", url: "attempts", icon: FileText },
      { title: "CALENDAR-EVENTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Calendar Events", url: "calendar-events", icon: FileText },
      { title: "CANDIDATES — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Candidates", url: "candidates", icon: FileText },
      { title: "COMPANY-STATE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Company State", url: "company-state", icon: FileText },
      { title: "DAILY-ATTENDANCE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Attendance Monitor", url: "daily-attendance", icon: FileText },
      { title: "DISCIPLINE-RECORDS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Discipline", url: "discipline-records", icon: FileText },
      { title: "EMPLOYEE-FILES — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Employee Files", url: "employee-files", icon: FileText },
      { title: "EMPLOYEE-PRODUCTIVITY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Employee Productivity", url: "employee-productivity", icon: FileText },
      { title: "EMPLOYEE-ZONE-HISTORY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Employee Zone History", url: "employee-zone-history", icon: FileText },
      { title: "EQUIPMENT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Equipment", url: "equipment", icon: FileText },
      { title: "EUROPRINT-CONTROL — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Europrint Control", url: "europrint-control", icon: FileText },
      { title: "GL — 1 ta", url: "", icon: FileText, separator: true },
      { title: "G L Documents", url: "gl", icon: FileText },
      { title: "IOT-SENSORS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Iot Sensors", url: "iot-sensors", icon: FileText },
      { title: "MACHINE-STATUS-CURRENT — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Machine Status", url: "machine-status-current", icon: FileText },
      { title: "MACHINE-STATUS-LOGS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Machine Status", url: "machine-status-logs", icon: FileText },
      { title: "MATERIAL-CARDS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Material Cards", url: "material-cards", icon: FileText },
      { title: "MENTORS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Mentors", url: "mentors", icon: FileText },
      { title: "MENTORSHIPS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Mentorships", url: "mentorships", icon: FileText },
      { title: "OKR — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Okr", url: "okr", icon: FileText },
      { title: "ORDER-STATUS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Order Status", url: "order-status", icon: FileText },
      { title: "ORG-DEPARTMENTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Org Departments", url: "org-departments", icon: FileText },
      { title: "PRODUCTION-FACTS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Production Facts", url: "production-facts", icon: FileText },
      { title: "PRODUCTION — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Shift Reports", url: "production/shift-reports", icon: FileText },
      { title: "QUALITY-DEFECTS-CAMERA — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Quality Defects Camera", url: "quality-defects-camera", icon: FileText },
      { title: "QUESTIONNAIRE-QUESTIONS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Questionnaire Questions", url: "questionnaire-questions", icon: FileText },
      { title: "QUESTIONS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Questions", url: "questions", icon: FileText },
      { title: "RACI-CRISIS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Raci Crisis", url: "raci-crisis", icon: FileText },
      { title: "RAW-MATERIALS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Raw Materials", url: "raw-materials", icon: FileText },
      { title: "SAFETY-VIOLATIONS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Safety Violations", url: "safety-violations", icon: FileText },
      { title: "USERS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Users", url: "users", icon: FileText },
      { title: "WASTE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Waste", url: "waste", icon: FileText },
      { title: "WEEKLY-PLANS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Weekly Plans", url: "weekly-plans", icon: FileText },
      { title: "WAREHOUSE-DIRECTORY — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Warehouse Directory", url: "warehouse-directory", icon: FileText },
      { title: "BARCODE-WAREHOUSE — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Barcode Warehouse", url: "barcode-warehouse", icon: FileText },
      { title: "MM — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Supply Chain Dashboard", url: "mm/supply-chain", icon: FileText },
      { title: "LOGISTICS — 1 ta", url: "", icon: FileText, separator: true },
      { title: "Logistics Dashboard", url: "logistics", icon: FileText },
    ],
  },
};
